// Localized chrome for the long-tail SEO pages: solution (/solutions/<slug>/),
// comparison (/compare/<slug>/ + hub), and glossary (/glossary/<slug>/ + hub).
// English is the source of truth; es/fr/de/pt/it mirror it. Templates use
// {name} / {category} / {date} / {term} placeholders filled at render.
//
// The per-entry copy (solution/competitor/glossary bodies) lives in the
// *_BY_LANG maps in solutions.ts / competitors.ts / glossary.ts; this file is
// only the shared section headings, labels, and CTAs.

import type { Lang } from "../i18n";

export interface Cap {
  title: string;
  body: string;
}

export interface LongtailChrome {
  // shared
  faq_h2: string;
  cta_kicker: string;
  cta_h2: string;
  cta_start_shopify: string;
  cta_start_woo: string;
  trial_note: string;
  hub_brands_h2: string; // "See why 20,000+ brands choose RevenueHunt."
  // solution detail
  sol_breadcrumb: string;
  sol_eyebrow: string; // "Solution" (prefix before chip)
  sol_cta_demo: string;
  sol_proof_brands: string;
  sol_proof_quizzes: string;
  sol_proof_revenue: string;
  sol_proof_reviews: string;
  sol_quiztypes_h2: string; // {name}
  sol_quiztypes_sub: string;
  sol_howhelps_h2: string; // {name}
  sol_seeitlive: string;
  sol_caps_h2: string;
  sol_caps: Cap[]; // 6
  sol_related_h2: string;
  sol_more_industries: string;
  sol_more_quiztypes: string;
  sol_view: string;
  // compare detail
  cmp_breadcrumb: string;
  cmp_eyebrow_prefix: string; // "Comparison · RevenueHunt vs" (+ category)
  cmp_cta_install: string;
  cmp_cta_demo: string;
  cmp_table_h2: string; // {name}
  cmp_table_sub: string;
  cmp_col_feature: string;
  cmp_yes: string;
  cmp_no: string;
  cmp_note: string; // {date} {name}
  cmp_why_h2: string; // {name}
  cmp_bestfor_h2: string; // {name}
  cmp_switch_h2: string; // {name}
  cmp_cta_start: string;
  cmp_cta_book: string;
  cmp_other_h2: string;
  cmp_see: string;
  // compare hub
  cmp_hub_eyebrow: string;
  cmp_hub_h1: string;
  cmp_hub_sub: string;
  cmp_hub_title: string;
  cmp_hub_desc: string;
  // glossary detail
  gl_breadcrumb: string;
  gl_eyebrow: string; // "Glossary" (prefix before chip)
  gl_reviewed: string; // {date}
  gl_with_rh_h2: string; // {term}
  gl_cta_start: string;
  gl_cta_how: string;
  gl_related_h2: string;
  gl_more_h2: string;
  gl_cta_h2: string;
  // glossary hub
  gl_hub_eyebrow: string;
  gl_hub_h1: string;
  gl_hub_sub: string;
  gl_hub_title: string;
  gl_hub_desc: string;
  gl_hub_terms_h2: string;
  gl_hub_read: string;
  gl_hub_guides_h2: string;
  gl_hub_guides_sub: string;
  gl_hub_readmore: string;
}

const en: LongtailChrome = {
  faq_h2: "Frequently asked questions",
  cta_kicker: "Most shoppers leave because they can't find the right product",
  cta_h2: "Turn shoppers into confident buyers with a Product Recommendation Quiz that drives sales.",
  cta_start_shopify: "start free on Shopify",
  cta_start_woo: "start free on WooCommerce",
  trial_note: "Free plan available · 15-day free trial · 30-day money-back guarantee",
  hub_brands_h2: "See why 20,000+ brands choose RevenueHunt.",
  sol_breadcrumb: "Solutions",
  sol_eyebrow: "Solution",
  sol_cta_demo: "see a live demo",
  sol_proof_brands: "brands",
  sol_proof_quizzes: "quizzes completed",
  sol_proof_revenue: "merchant revenue",
  sol_proof_reviews: "550+ reviews",
  sol_quiztypes_h2: "Popular {name} quiz types",
  sol_quiztypes_sub: "Common patterns merchants build with RevenueHunt. Mix and match them in a single quiz.",
  sol_howhelps_h2: "What a {name} quiz does for your store",
  sol_seeitlive: "See it live",
  sol_caps_h2: "Everything a RevenueHunt quiz includes",
  sol_caps: [
    { title: "Free to start", body: "A genuinely free plan with 100 responses a month, on live stores. Paid plans from $39/month." },
    { title: "AI Quiz Copilot", body: "Describe your store and the Copilot scaffolds a full quiz, logic and product mappings, in about 60 seconds." },
    { title: "Real-time catalog sync", body: "Recommends real products and variants from your live catalog, kept in sync automatically." },
    { title: "Unlimited quizzes & logic", body: "Build as many quizzes as you want on every plan, with unlimited conditional and branching logic." },
    { title: "Klaviyo & email sync", body: "Answers and customer tags flow to Klaviyo, Mailchimp, Omnisend, HubSpot, and more for segmentation." },
    { title: "Drop-off analytics", body: "See question-by-question drop-off so you can fix friction and recover lost responses." },
  ],
  sol_related_h2: "Related solutions & resources",
  sol_more_industries: "More industries",
  sol_more_quiztypes: "More quiz types",
  sol_view: "View solution",
  cmp_breadcrumb: "Compare",
  cmp_eyebrow_prefix: "Comparison · RevenueHunt vs",
  cmp_cta_install: "install on Shopify",
  cmp_cta_demo: "see a live demo",
  cmp_table_h2: "RevenueHunt vs {name} at a glance",
  cmp_table_sub: "The features that matter most for a Shopify product quiz.",
  cmp_col_feature: "Feature",
  cmp_yes: "Yes",
  cmp_no: "No",
  cmp_note: "Comparison based on publicly available information from each vendor as of {date}. {name} pricing and features may have changed since, so check their site for the latest.",
  cmp_why_h2: "Why merchants choose RevenueHunt over {name}",
  cmp_bestfor_h2: "When {name} might be the better fit",
  cmp_switch_h2: "Switching from {name}",
  cmp_cta_start: "start free on Shopify",
  cmp_cta_book: "book a demo",
  cmp_other_h2: "Compare other quiz tools",
  cmp_see: "See comparison",
  cmp_hub_eyebrow: "Comparisons",
  cmp_hub_h1: "RevenueHunt vs the alternatives",
  cmp_hub_sub: "How RevenueHunt stacks up against other product quiz, guided-selling, and personalization tools, on pricing, features, and the platforms you sell on. Honest, up-to-date comparisons.",
  cmp_hub_title: "RevenueHunt vs the alternatives: compare quiz tools",
  cmp_hub_desc: "See how RevenueHunt compares to Octane AI, Typeform, Zoovu, Nosto, Jebbit, and Tolstoy on pricing, features, and platforms for product recommendation quizzes.",
  gl_breadcrumb: "Glossary",
  gl_eyebrow: "Glossary",
  gl_reviewed: "Last reviewed {date}",
  gl_with_rh_h2: "{term} with RevenueHunt",
  gl_cta_start: "start free on Shopify",
  gl_cta_how: "see how it works",
  gl_related_h2: "Related reading",
  gl_more_h2: "More glossary terms",
  gl_cta_h2: "Put it into practice with a product recommendation quiz.",
  gl_hub_eyebrow: "Glossary",
  gl_hub_h1: "Quiz and personalization glossary",
  gl_hub_sub: "Plain-English definitions of the terms behind product quizzes and ecommerce personalization. No jargon, no fluff, just what each one means and why it matters.",
  gl_hub_title: "Quiz & personalization glossary",
  gl_hub_desc: "Plain-English definitions of the quiz and personalization terms in ecommerce: conversational commerce, product discovery, quiz funnels, and more.",
  gl_hub_terms_h2: "Terms",
  gl_hub_read: "Read definition",
  gl_hub_guides_h2: "Guides and tools",
  gl_hub_guides_sub: "Deeper guides on the topics above, and a calculator to size the opportunity for your store.",
  gl_hub_readmore: "Read more",
};

const es: LongtailChrome = {
  faq_h2: "Preguntas frecuentes",
  cta_kicker: "La mayoría de los compradores se van porque no encuentran el producto adecuado",
  cta_h2: "Convierte a tus compradores en clientes seguros con un quiz de recomendación de productos que impulsa las ventas.",
  cta_start_shopify: "empieza gratis en Shopify",
  cta_start_woo: "empieza gratis en WooCommerce",
  trial_note: "Plan gratuito disponible · prueba gratis de 15 días · garantía de devolución de 30 días",
  hub_brands_h2: "Descubre por qué más de 20.000 marcas eligen RevenueHunt.",
  sol_breadcrumb: "Soluciones",
  sol_eyebrow: "Solución",
  sol_cta_demo: "ver una demo en directo",
  sol_proof_brands: "marcas",
  sol_proof_quizzes: "quizzes completados",
  sol_proof_revenue: "ingresos de comerciantes",
  sol_proof_reviews: "más de 550 reseñas",
  sol_quiztypes_h2: "Tipos de quiz populares de {name}",
  sol_quiztypes_sub: "Patrones habituales que los comerciantes crean con RevenueHunt. Combínalos en un mismo quiz.",
  sol_howhelps_h2: "Lo que un quiz de {name} hace por tu tienda",
  sol_seeitlive: "Míralo en directo",
  sol_caps_h2: "Todo lo que incluye un quiz de RevenueHunt",
  sol_caps: [
    { title: "Gratis para empezar", body: "Un plan realmente gratuito con 100 respuestas al mes, en tiendas reales. Planes de pago desde $39/month." },
    { title: "AI Quiz Copilot", body: "Describe tu tienda y el Copilot crea un quiz completo, con su lógica y la asignación de productos, en unos 60 segundos." },
    { title: "Sincronización del catálogo en tiempo real", body: "Recomienda productos y variantes reales de tu catálogo en directo, sincronizados automáticamente." },
    { title: "Quizzes y lógica ilimitados", body: "Crea todos los quizzes que quieras en cualquier plan, con lógica condicional y de ramificación ilimitada." },
    { title: "Sincronización con Klaviyo y email", body: "Las respuestas y las etiquetas de cliente llegan a Klaviyo, Mailchimp, Omnisend, HubSpot y más para segmentar." },
    { title: "Analítica de abandono", body: "Consulta el abandono pregunta a pregunta para corregir fricciones y recuperar respuestas perdidas." },
  ],
  sol_related_h2: "Soluciones y recursos relacionados",
  sol_more_industries: "Más sectores",
  sol_more_quiztypes: "Más tipos de quiz",
  sol_view: "Ver solución",
  cmp_breadcrumb: "Comparar",
  cmp_eyebrow_prefix: "Comparación · RevenueHunt vs",
  cmp_cta_install: "instalar en Shopify",
  cmp_cta_demo: "ver una demo en directo",
  cmp_table_h2: "RevenueHunt vs {name} de un vistazo",
  cmp_table_sub: "Las funciones que más importan en un quiz de productos para Shopify.",
  cmp_col_feature: "Función",
  cmp_yes: "Sí",
  cmp_no: "No",
  cmp_note: "Comparación basada en información pública de cada proveedor a fecha de {date}. Los precios y funciones de {name} pueden haber cambiado desde entonces, así que consulta su sitio para ver lo más reciente.",
  cmp_why_h2: "Por qué los comerciantes eligen RevenueHunt frente a {name}",
  cmp_bestfor_h2: "Cuándo {name} puede encajar mejor",
  cmp_switch_h2: "Cambiar desde {name}",
  cmp_cta_start: "empieza gratis en Shopify",
  cmp_cta_book: "reservar una demo",
  cmp_other_h2: "Compara otras herramientas de quiz",
  cmp_see: "Ver comparación",
  cmp_hub_eyebrow: "Comparaciones",
  cmp_hub_h1: "RevenueHunt frente a las alternativas",
  cmp_hub_sub: "Cómo se compara RevenueHunt con otras herramientas de quiz de productos, venta guiada y personalización, en precios, funciones y las plataformas en las que vendes. Comparaciones honestas y actualizadas.",
  cmp_hub_title: "RevenueHunt frente a las alternativas: compara herramientas de quiz",
  cmp_hub_desc: "Descubre cómo se compara RevenueHunt con Octane AI, Typeform, Zoovu, Nosto, Jebbit y Tolstoy en precios, funciones y plataformas para quizzes de recomendación de productos.",
  gl_breadcrumb: "Glosario",
  gl_eyebrow: "Glosario",
  gl_reviewed: "Última revisión {date}",
  gl_with_rh_h2: "{term} con RevenueHunt",
  gl_cta_start: "empieza gratis en Shopify",
  gl_cta_how: "ver cómo funciona",
  gl_related_h2: "Lecturas relacionadas",
  gl_more_h2: "Más términos del glosario",
  gl_cta_h2: "Ponlo en práctica con un quiz de recomendación de productos.",
  gl_hub_eyebrow: "Glosario",
  gl_hub_h1: "Glosario de quiz y personalización",
  gl_hub_sub: "Definiciones claras de los términos detrás de los quizzes de productos y la personalización en ecommerce. Sin jerga ni paja, solo lo que significa cada uno y por qué importa.",
  gl_hub_title: "Glosario de quiz y personalización",
  gl_hub_desc: "Definiciones claras de los términos de quiz y personalización en ecommerce: comercio conversacional, descubrimiento de productos, embudos de quiz y más.",
  gl_hub_terms_h2: "Términos",
  gl_hub_read: "Leer definición",
  gl_hub_guides_h2: "Guías y herramientas",
  gl_hub_guides_sub: "Guías más profundas sobre los temas de arriba, y una calculadora para dimensionar la oportunidad de tu tienda.",
  gl_hub_readmore: "Leer más",
};

const fr: LongtailChrome = {
  faq_h2: "Questions fréquentes",
  cta_kicker: "La plupart des clients partent parce qu'ils ne trouvent pas le bon produit",
  cta_h2: "Transformez vos clients en acheteurs confiants avec un quiz de recommandation de produits qui génère des ventes.",
  cta_start_shopify: "commencez gratuitement sur Shopify",
  cta_start_woo: "commencez gratuitement sur WooCommerce",
  trial_note: "Offre gratuite disponible · essai gratuit de 15 jours · garantie de remboursement de 30 jours",
  hub_brands_h2: "Découvrez pourquoi plus de 20 000 marques choisissent RevenueHunt.",
  sol_breadcrumb: "Solutions",
  sol_eyebrow: "Solution",
  sol_cta_demo: "voir une démo en direct",
  sol_proof_brands: "marques",
  sol_proof_quizzes: "quiz complétés",
  sol_proof_revenue: "chiffre d'affaires des marchands",
  sol_proof_reviews: "plus de 550 avis",
  sol_quiztypes_h2: "Types de quiz {name} populaires",
  sol_quiztypes_sub: "Modèles courants que les marchands créent avec RevenueHunt. Combinez-les dans un même quiz.",
  sol_howhelps_h2: "Ce qu'un quiz {name} apporte à votre boutique",
  sol_seeitlive: "Voir en direct",
  sol_caps_h2: "Tout ce qu'inclut un quiz RevenueHunt",
  sol_caps: [
    { title: "Gratuit pour démarrer", body: "Une offre vraiment gratuite avec 100 réponses par mois, sur des boutiques en ligne. Offres payantes à partir de $39/month." },
    { title: "AI Quiz Copilot", body: "Décrivez votre boutique et le Copilot structure un quiz complet, sa logique et l'association des produits, en environ 60 secondes." },
    { title: "Synchronisation du catalogue en temps réel", body: "Recommande de vrais produits et variantes de votre catalogue en direct, synchronisés automatiquement." },
    { title: "Quiz et logique illimités", body: "Créez autant de quiz que vous le souhaitez sur chaque offre, avec une logique conditionnelle et de branchement illimitée." },
    { title: "Synchronisation Klaviyo et e-mail", body: "Les réponses et les tags client sont transmis à Klaviyo, Mailchimp, Omnisend, HubSpot et plus pour la segmentation." },
    { title: "Analyse des abandons", body: "Visualisez les abandons question par question pour corriger les frictions et récupérer les réponses perdues." },
  ],
  sol_related_h2: "Solutions et ressources associées",
  sol_more_industries: "Plus de secteurs",
  sol_more_quiztypes: "Plus de types de quiz",
  sol_view: "Voir la solution",
  cmp_breadcrumb: "Comparer",
  cmp_eyebrow_prefix: "Comparaison · RevenueHunt vs",
  cmp_cta_install: "installer sur Shopify",
  cmp_cta_demo: "voir une démo en direct",
  cmp_table_h2: "RevenueHunt vs {name} en un coup d'œil",
  cmp_table_sub: "Les fonctionnalités qui comptent le plus pour un quiz produit Shopify.",
  cmp_col_feature: "Fonctionnalité",
  cmp_yes: "Oui",
  cmp_no: "Non",
  cmp_note: "Comparaison établie à partir des informations publiques de chaque fournisseur en date du {date}. Les prix et fonctionnalités de {name} ont pu changer depuis, consultez donc leur site pour les dernières informations.",
  cmp_why_h2: "Pourquoi les marchands choisissent RevenueHunt plutôt que {name}",
  cmp_bestfor_h2: "Quand {name} peut être le meilleur choix",
  cmp_switch_h2: "Passer de {name}",
  cmp_cta_start: "commencez gratuitement sur Shopify",
  cmp_cta_book: "réserver une démo",
  cmp_other_h2: "Comparer d'autres outils de quiz",
  cmp_see: "Voir la comparaison",
  cmp_hub_eyebrow: "Comparaisons",
  cmp_hub_h1: "RevenueHunt face aux alternatives",
  cmp_hub_sub: "Comment RevenueHunt se positionne face aux autres outils de quiz produit, de vente guidée et de personnalisation, sur les prix, les fonctionnalités et les plateformes où vous vendez. Des comparaisons honnêtes et à jour.",
  cmp_hub_title: "RevenueHunt face aux alternatives : comparez les outils de quiz",
  cmp_hub_desc: "Découvrez comment RevenueHunt se compare à Octane AI, Typeform, Zoovu, Nosto, Jebbit et Tolstoy sur les prix, les fonctionnalités et les plateformes pour les quiz de recommandation de produits.",
  gl_breadcrumb: "Glossaire",
  gl_eyebrow: "Glossaire",
  gl_reviewed: "Dernière révision le {date}",
  gl_with_rh_h2: "{term} avec RevenueHunt",
  gl_cta_start: "commencez gratuitement sur Shopify",
  gl_cta_how: "voir comment ça marche",
  gl_related_h2: "Lectures associées",
  gl_more_h2: "Plus de termes du glossaire",
  gl_cta_h2: "Mettez-le en pratique avec un quiz de recommandation de produits.",
  gl_hub_eyebrow: "Glossaire",
  gl_hub_h1: "Glossaire du quiz et de la personnalisation",
  gl_hub_sub: "Des définitions claires des termes derrière les quiz produit et la personnalisation e-commerce. Sans jargon ni remplissage, juste ce que chacun signifie et pourquoi il compte.",
  gl_hub_title: "Glossaire du quiz et de la personnalisation",
  gl_hub_desc: "Des définitions claires des termes de quiz et de personnalisation en e-commerce : commerce conversationnel, découverte de produits, tunnels de quiz et plus.",
  gl_hub_terms_h2: "Termes",
  gl_hub_read: "Lire la définition",
  gl_hub_guides_h2: "Guides et outils",
  gl_hub_guides_sub: "Des guides plus approfondis sur les sujets ci-dessus, et un calculateur pour mesurer le potentiel de votre boutique.",
  gl_hub_readmore: "Lire la suite",
};

const de: LongtailChrome = {
  faq_h2: "Häufig gestellte Fragen",
  cta_kicker: "Die meisten Kunden gehen, weil sie das richtige Produkt nicht finden",
  cta_h2: "Mach aus deinen Kunden sichere Käufer mit einem Produktempfehlungs-Quiz, das den Umsatz steigert.",
  cta_start_shopify: "kostenlos starten auf Shopify",
  cta_start_woo: "kostenlos starten auf WooCommerce",
  trial_note: "Kostenloser Plan verfügbar · 15 Tage kostenlos testen · 30 Tage Geld-zurück-Garantie",
  hub_brands_h2: "Erfahre, warum sich über 20.000 Marken für RevenueHunt entscheiden.",
  sol_breadcrumb: "Lösungen",
  sol_eyebrow: "Lösung",
  sol_cta_demo: "Live-Demo ansehen",
  sol_proof_brands: "Marken",
  sol_proof_quizzes: "abgeschlossene Quizze",
  sol_proof_revenue: "Händlerumsatz",
  sol_proof_reviews: "über 550 Bewertungen",
  sol_quiztypes_h2: "Beliebte {name}-Quiz-Typen",
  sol_quiztypes_sub: "Gängige Muster, die Händler mit RevenueHunt erstellen. Kombiniere sie in einem einzigen Quiz.",
  sol_howhelps_h2: "Was ein {name}-Quiz für deinen Shop leistet",
  sol_seeitlive: "Live ansehen",
  sol_caps_h2: "Alles, was ein RevenueHunt-Quiz enthält",
  sol_caps: [
    { title: "Kostenlos starten", body: "Ein wirklich kostenloser Plan mit 100 Antworten pro Monat, in Live-Shops. Bezahlpläne ab $39/month." },
    { title: "AI Quiz Copilot", body: "Beschreibe deinen Shop und der Copilot baut ein komplettes Quiz, die Logik und die Produktzuordnungen in etwa 60 Sekunden." },
    { title: "Echtzeit-Katalogsynchronisierung", body: "Empfiehlt echte Produkte und Varianten aus deinem Live-Katalog, automatisch synchron gehalten." },
    { title: "Unbegrenzte Quizze & Logik", body: "Erstelle so viele Quizze, wie du möchtest, in jedem Plan, mit unbegrenzter bedingter und verzweigter Logik." },
    { title: "Klaviyo- & E-Mail-Sync", body: "Antworten und Kunden-Tags fließen zur Segmentierung an Klaviyo, Mailchimp, Omnisend, HubSpot und mehr." },
    { title: "Abbruch-Analyse", body: "Sieh den Abbruch Frage für Frage, um Reibung zu beheben und verlorene Antworten zurückzugewinnen." },
  ],
  sol_related_h2: "Verwandte Lösungen & Ressourcen",
  sol_more_industries: "Weitere Branchen",
  sol_more_quiztypes: "Weitere Quiz-Typen",
  sol_view: "Lösung ansehen",
  cmp_breadcrumb: "Vergleichen",
  cmp_eyebrow_prefix: "Vergleich · RevenueHunt vs",
  cmp_cta_install: "auf Shopify installieren",
  cmp_cta_demo: "Live-Demo ansehen",
  cmp_table_h2: "RevenueHunt vs {name} auf einen Blick",
  cmp_table_sub: "Die Funktionen, die für ein Shopify-Produktquiz am wichtigsten sind.",
  cmp_col_feature: "Funktion",
  cmp_yes: "Ja",
  cmp_no: "Nein",
  cmp_note: "Vergleich auf Basis öffentlich verfügbarer Informationen jedes Anbieters mit Stand {date}. Preise und Funktionen von {name} können sich seither geändert haben, prüfe daher die Website für den aktuellen Stand.",
  cmp_why_h2: "Warum Händler RevenueHunt {name} vorziehen",
  cmp_bestfor_h2: "Wann {name} die bessere Wahl sein kann",
  cmp_switch_h2: "Wechsel von {name}",
  cmp_cta_start: "kostenlos starten auf Shopify",
  cmp_cta_book: "Demo buchen",
  cmp_other_h2: "Weitere Quiz-Tools vergleichen",
  cmp_see: "Vergleich ansehen",
  cmp_hub_eyebrow: "Vergleiche",
  cmp_hub_h1: "RevenueHunt im Vergleich zu den Alternativen",
  cmp_hub_sub: "Wie sich RevenueHunt gegen andere Tools für Produktquiz, Guided Selling und Personalisierung schlägt, bei Preisen, Funktionen und den Plattformen, auf denen du verkaufst. Ehrliche, aktuelle Vergleiche.",
  cmp_hub_title: "RevenueHunt im Vergleich zu den Alternativen: Quiz-Tools vergleichen",
  cmp_hub_desc: "Sieh, wie RevenueHunt im Vergleich zu Octane AI, Typeform, Zoovu, Nosto, Jebbit und Tolstoy bei Preisen, Funktionen und Plattformen für Produktempfehlungs-Quizze abschneidet.",
  gl_breadcrumb: "Glossar",
  gl_eyebrow: "Glossar",
  gl_reviewed: "Zuletzt geprüft {date}",
  gl_with_rh_h2: "{term} mit RevenueHunt",
  gl_cta_start: "kostenlos starten auf Shopify",
  gl_cta_how: "ansehen, wie es funktioniert",
  gl_related_h2: "Weiterführende Lektüre",
  gl_more_h2: "Weitere Glossarbegriffe",
  gl_cta_h2: "Setze es mit einem Produktempfehlungs-Quiz in die Praxis um.",
  gl_hub_eyebrow: "Glossar",
  gl_hub_h1: "Glossar zu Quiz und Personalisierung",
  gl_hub_sub: "Verständliche Definitionen der Begriffe hinter Produktquizzen und E-Commerce-Personalisierung. Kein Fachjargon, kein Füllwerk, nur was jeder bedeutet und warum er wichtig ist.",
  gl_hub_title: "Glossar zu Quiz & Personalisierung",
  gl_hub_desc: "Verständliche Definitionen der Quiz- und Personalisierungsbegriffe im E-Commerce: Conversational Commerce, Produktentdeckung, Quiz-Funnels und mehr.",
  gl_hub_terms_h2: "Begriffe",
  gl_hub_read: "Definition lesen",
  gl_hub_guides_h2: "Leitfäden und Tools",
  gl_hub_guides_sub: "Tiefergehende Leitfäden zu den Themen oben, und ein Rechner, um das Potenzial für deinen Shop zu bemessen.",
  gl_hub_readmore: "Mehr lesen",
};

const pt: LongtailChrome = {
  faq_h2: "Perguntas frequentes",
  cta_kicker: "A maioria dos compradores vai-se embora porque não encontra o produto certo",
  cta_h2: "Transforma os teus compradores em clientes confiantes com um quiz de recomendação de produtos que impulsiona as vendas.",
  cta_start_shopify: "começa grátis na Shopify",
  cta_start_woo: "começa grátis na WooCommerce",
  trial_note: "Plano gratuito disponível · teste grátis de 15 dias · garantia de devolução de 30 dias",
  hub_brands_h2: "Descobre porque mais de 20.000 marcas escolhem a RevenueHunt.",
  sol_breadcrumb: "Soluções",
  sol_eyebrow: "Solução",
  sol_cta_demo: "ver uma demo ao vivo",
  sol_proof_brands: "marcas",
  sol_proof_quizzes: "quizzes concluídos",
  sol_proof_revenue: "receita dos comerciantes",
  sol_proof_reviews: "mais de 550 avaliações",
  sol_quiztypes_h2: "Tipos de quiz {name} populares",
  sol_quiztypes_sub: "Padrões comuns que os comerciantes criam com a RevenueHunt. Combina-os num único quiz.",
  sol_howhelps_h2: "O que um quiz de {name} faz pela tua loja",
  sol_seeitlive: "Vê ao vivo",
  sol_caps_h2: "Tudo o que um quiz da RevenueHunt inclui",
  sol_caps: [
    { title: "Grátis para começar", body: "Um plano genuinamente gratuito com 100 respostas por mês, em lojas reais. Planos pagos a partir de $39/month." },
    { title: "AI Quiz Copilot", body: "Descreve a tua loja e o Copilot estrutura um quiz completo, a lógica e a associação de produtos, em cerca de 60 segundos." },
    { title: "Sincronização do catálogo em tempo real", body: "Recomenda produtos e variantes reais do teu catálogo ao vivo, mantidos em sincronia automaticamente." },
    { title: "Quizzes e lógica ilimitados", body: "Cria tantos quizzes quantos quiseres em qualquer plano, com lógica condicional e de ramificação ilimitada." },
    { title: "Sincronização com Klaviyo e email", body: "As respostas e as tags de cliente seguem para Klaviyo, Mailchimp, Omnisend, HubSpot e mais para segmentação." },
    { title: "Analítica de abandono", body: "Vê o abandono pergunta a pergunta para corrigir fricções e recuperar respostas perdidas." },
  ],
  sol_related_h2: "Soluções e recursos relacionados",
  sol_more_industries: "Mais setores",
  sol_more_quiztypes: "Mais tipos de quiz",
  sol_view: "Ver solução",
  cmp_breadcrumb: "Comparar",
  cmp_eyebrow_prefix: "Comparação · RevenueHunt vs",
  cmp_cta_install: "instalar na Shopify",
  cmp_cta_demo: "ver uma demo ao vivo",
  cmp_table_h2: "RevenueHunt vs {name} num relance",
  cmp_table_sub: "As funcionalidades que mais importam num quiz de produtos para Shopify.",
  cmp_col_feature: "Funcionalidade",
  cmp_yes: "Sim",
  cmp_no: "Não",
  cmp_note: "Comparação baseada em informação publicamente disponível de cada fornecedor à data de {date}. Os preços e funcionalidades da {name} podem ter mudado desde então, por isso consulta o site para as novidades.",
  cmp_why_h2: "Porque os comerciantes escolhem a RevenueHunt em vez da {name}",
  cmp_bestfor_h2: "Quando a {name} pode ser a melhor opção",
  cmp_switch_h2: "Mudar da {name}",
  cmp_cta_start: "começa grátis na Shopify",
  cmp_cta_book: "marcar uma demo",
  cmp_other_h2: "Compara outras ferramentas de quiz",
  cmp_see: "Ver comparação",
  cmp_hub_eyebrow: "Comparações",
  cmp_hub_h1: "RevenueHunt face às alternativas",
  cmp_hub_sub: "Como a RevenueHunt se compara com outras ferramentas de quiz de produtos, venda guiada e personalização, em preços, funcionalidades e nas plataformas onde vendes. Comparações honestas e atualizadas.",
  cmp_hub_title: "RevenueHunt face às alternativas: compara ferramentas de quiz",
  cmp_hub_desc: "Vê como a RevenueHunt se compara com Octane AI, Typeform, Zoovu, Nosto, Jebbit e Tolstoy em preços, funcionalidades e plataformas para quizzes de recomendação de produtos.",
  gl_breadcrumb: "Glossário",
  gl_eyebrow: "Glossário",
  gl_reviewed: "Última revisão {date}",
  gl_with_rh_h2: "{term} com a RevenueHunt",
  gl_cta_start: "começa grátis na Shopify",
  gl_cta_how: "ver como funciona",
  gl_related_h2: "Leituras relacionadas",
  gl_more_h2: "Mais termos do glossário",
  gl_cta_h2: "Põe em prática com um quiz de recomendação de produtos.",
  gl_hub_eyebrow: "Glossário",
  gl_hub_h1: "Glossário de quiz e personalização",
  gl_hub_sub: "Definições claras dos termos por trás dos quizzes de produtos e da personalização em ecommerce. Sem jargão nem enchimento, apenas o que cada um significa e porque importa.",
  gl_hub_title: "Glossário de quiz e personalização",
  gl_hub_desc: "Definições claras dos termos de quiz e personalização em ecommerce: comércio conversacional, descoberta de produtos, funis de quiz e mais.",
  gl_hub_terms_h2: "Termos",
  gl_hub_read: "Ler definição",
  gl_hub_guides_h2: "Guias e ferramentas",
  gl_hub_guides_sub: "Guias mais aprofundados sobre os temas acima, e uma calculadora para dimensionar a oportunidade da tua loja.",
  gl_hub_readmore: "Ler mais",
};

const it: LongtailChrome = {
  faq_h2: "Domande frequenti",
  cta_kicker: "La maggior parte dei clienti se ne va perché non trova il prodotto giusto",
  cta_h2: "Trasforma i tuoi clienti in acquirenti sicuri con un quiz di raccomandazione dei prodotti che fa crescere le vendite.",
  cta_start_shopify: "inizia gratis su Shopify",
  cta_start_woo: "inizia gratis su WooCommerce",
  trial_note: "Piano gratuito disponibile · prova gratuita di 15 giorni · garanzia di rimborso di 30 giorni",
  hub_brands_h2: "Scopri perché oltre 20.000 brand scelgono RevenueHunt.",
  sol_breadcrumb: "Soluzioni",
  sol_eyebrow: "Soluzione",
  sol_cta_demo: "guarda una demo dal vivo",
  sol_proof_brands: "brand",
  sol_proof_quizzes: "quiz completati",
  sol_proof_revenue: "fatturato dei merchant",
  sol_proof_reviews: "oltre 550 recensioni",
  sol_quiztypes_h2: "Tipi di quiz {name} più diffusi",
  sol_quiztypes_sub: "Schemi comuni che i merchant creano con RevenueHunt. Combinali in un unico quiz.",
  sol_howhelps_h2: "Cosa fa un quiz {name} per il tuo store",
  sol_seeitlive: "Guardalo dal vivo",
  sol_caps_h2: "Tutto ciò che include un quiz RevenueHunt",
  sol_caps: [
    { title: "Gratis per iniziare", body: "Un piano davvero gratuito con 100 risposte al mese, su store reali. Piani a pagamento da $39/month." },
    { title: "AI Quiz Copilot", body: "Descrivi il tuo store e il Copilot imposta un quiz completo, la logica e l'associazione dei prodotti, in circa 60 secondi." },
    { title: "Sincronizzazione del catalogo in tempo reale", body: "Consiglia prodotti e varianti reali dal tuo catalogo dal vivo, mantenuti sincronizzati automaticamente." },
    { title: "Quiz e logica illimitati", body: "Crea tutti i quiz che vuoi su ogni piano, con logica condizionale e di ramificazione illimitata." },
    { title: "Sincronizzazione con Klaviyo ed email", body: "Risposte e tag cliente passano a Klaviyo, Mailchimp, Omnisend, HubSpot e altri per la segmentazione." },
    { title: "Analisi degli abbandoni", body: "Visualizza gli abbandoni domanda per domanda per ridurre gli attriti e recuperare le risposte perse." },
  ],
  sol_related_h2: "Soluzioni e risorse correlate",
  sol_more_industries: "Altri settori",
  sol_more_quiztypes: "Altri tipi di quiz",
  sol_view: "Vedi soluzione",
  cmp_breadcrumb: "Confronta",
  cmp_eyebrow_prefix: "Confronto · RevenueHunt vs",
  cmp_cta_install: "installa su Shopify",
  cmp_cta_demo: "guarda una demo dal vivo",
  cmp_table_h2: "RevenueHunt vs {name} in breve",
  cmp_table_sub: "Le funzionalità che contano di più per un quiz prodotti su Shopify.",
  cmp_col_feature: "Funzionalità",
  cmp_yes: "Sì",
  cmp_no: "No",
  cmp_note: "Confronto basato su informazioni pubblicamente disponibili di ciascun fornitore alla data del {date}. I prezzi e le funzionalità di {name} potrebbero essere cambiati da allora, quindi controlla il loro sito per le ultime novità.",
  cmp_why_h2: "Perché i merchant scelgono RevenueHunt invece di {name}",
  cmp_bestfor_h2: "Quando {name} può essere la scelta migliore",
  cmp_switch_h2: "Passare da {name}",
  cmp_cta_start: "inizia gratis su Shopify",
  cmp_cta_book: "prenota una demo",
  cmp_other_h2: "Confronta altri strumenti per quiz",
  cmp_see: "Vedi confronto",
  cmp_hub_eyebrow: "Confronti",
  cmp_hub_h1: "RevenueHunt rispetto alle alternative",
  cmp_hub_sub: "Come RevenueHunt si confronta con altri strumenti di quiz prodotti, vendita guidata e personalizzazione, su prezzi, funzionalità e le piattaforme su cui vendi. Confronti onesti e aggiornati.",
  cmp_hub_title: "RevenueHunt rispetto alle alternative: confronta gli strumenti per quiz",
  cmp_hub_desc: "Scopri come RevenueHunt si confronta con Octane AI, Typeform, Zoovu, Nosto, Jebbit e Tolstoy su prezzi, funzionalità e piattaforme per i quiz di raccomandazione dei prodotti.",
  gl_breadcrumb: "Glossario",
  gl_eyebrow: "Glossario",
  gl_reviewed: "Ultima revisione {date}",
  gl_with_rh_h2: "{term} con RevenueHunt",
  gl_cta_start: "inizia gratis su Shopify",
  gl_cta_how: "guarda come funziona",
  gl_related_h2: "Letture correlate",
  gl_more_h2: "Altri termini del glossario",
  gl_cta_h2: "Mettilo in pratica con un quiz di raccomandazione dei prodotti.",
  gl_hub_eyebrow: "Glossario",
  gl_hub_h1: "Glossario di quiz e personalizzazione",
  gl_hub_sub: "Definizioni chiare dei termini dietro i quiz prodotti e la personalizzazione nell'ecommerce. Niente gergo né riempitivi, solo cosa significa ciascuno e perché conta.",
  gl_hub_title: "Glossario di quiz e personalizzazione",
  gl_hub_desc: "Definizioni chiare dei termini di quiz e personalizzazione nell'ecommerce: commercio conversazionale, scoperta dei prodotti, funnel di quiz e altro.",
  gl_hub_terms_h2: "Termini",
  gl_hub_read: "Leggi la definizione",
  gl_hub_guides_h2: "Guide e strumenti",
  gl_hub_guides_sub: "Guide più approfondite sui temi qui sopra, e un calcolatore per dimensionare l'opportunità per il tuo store.",
  gl_hub_readmore: "Leggi di più",
};

const nl: LongtailChrome = {
  faq_h2: "Veelgestelde vragen",
  cta_kicker: "De meeste shoppers haken af omdat ze het juiste product niet vinden",
  cta_h2: "Maak van shoppers zelfverzekerde kopers met een productaanbevelingsquiz die de verkoop stimuleert.",
  cta_start_shopify: "begin gratis op Shopify",
  cta_start_woo: "begin gratis op WooCommerce",
  trial_note: "Gratis plan beschikbaar · 15 dagen gratis proberen · 30 dagen niet-goed-geld-terug",
  hub_brands_h2: "Ontdek waarom 20.000+ merken voor RevenueHunt kiezen.",
  sol_breadcrumb: "Oplossingen",
  sol_eyebrow: "Oplossing",
  sol_cta_demo: "bekijk een live demo",
  sol_proof_brands: "merken",
  sol_proof_quizzes: "voltooide quizzen",
  sol_proof_revenue: "omzet van verkopers",
  sol_proof_reviews: "550+ reviews",
  sol_quiztypes_h2: "Populaire {name}-quiztypes",
  sol_quiztypes_sub: "Veelgebruikte patronen die verkopers met RevenueHunt bouwen. Combineer ze in één quiz.",
  sol_howhelps_h2: "Wat een {name}-quiz voor je winkel doet",
  sol_seeitlive: "Bekijk het live",
  sol_caps_h2: "Alles wat een RevenueHunt-quiz bevat",
  sol_caps: [
    { title: "Gratis om te starten", body: "Een echt gratis plan met 100 reacties per maand, op live winkels. Betaalde plannen vanaf $39/month." },
    { title: "AI Quiz Copilot", body: "Beschrijf je winkel en de Copilot zet in ongeveer 60 seconden een volledige quiz op, met logica en productkoppelingen." },
    { title: "Real-time catalogussync", body: "Beveelt echte producten en varianten uit je live catalogus aan, automatisch gesynchroniseerd." },
    { title: "Onbeperkte quizzen & logica", body: "Bouw zoveel quizzen als je wilt op elk plan, met onbeperkte voorwaardelijke en vertakkende logica." },
    { title: "Klaviyo- & e-mailsync", body: "Antwoorden en klanttags stromen naar Klaviyo, Mailchimp, Omnisend, HubSpot en meer voor segmentatie." },
    { title: "Uitval-analyse", body: "Zie de uitval vraag voor vraag, zodat je frictie wegneemt en verloren reacties terugwint." },
  ],
  sol_related_h2: "Gerelateerde oplossingen & bronnen",
  sol_more_industries: "Meer branches",
  sol_more_quiztypes: "Meer quiztypes",
  sol_view: "Bekijk oplossing",
  cmp_breadcrumb: "Vergelijken",
  cmp_eyebrow_prefix: "Vergelijking · RevenueHunt vs",
  cmp_cta_install: "installeer op Shopify",
  cmp_cta_demo: "bekijk een live demo",
  cmp_table_h2: "RevenueHunt vs {name} in één oogopslag",
  cmp_table_sub: "De functies die het belangrijkst zijn voor een Shopify-productquiz.",
  cmp_col_feature: "Functie",
  cmp_yes: "Ja",
  cmp_no: "Nee",
  cmp_note: "Vergelijking op basis van publiek beschikbare informatie van elke aanbieder per {date}. De prijzen en functies van {name} kunnen sindsdien zijn veranderd, dus check hun site voor het laatste nieuws.",
  cmp_why_h2: "Waarom verkopers RevenueHunt verkiezen boven {name}",
  cmp_bestfor_h2: "Wanneer {name} beter past",
  cmp_switch_h2: "Overstappen van {name}",
  cmp_cta_start: "begin gratis op Shopify",
  cmp_cta_book: "boek een demo",
  cmp_other_h2: "Vergelijk andere quiztools",
  cmp_see: "Bekijk vergelijking",
  cmp_hub_eyebrow: "Vergelijkingen",
  cmp_hub_h1: "RevenueHunt vs de alternatieven",
  cmp_hub_sub: "Hoe RevenueHunt zich verhoudt tot andere tools voor productquizzen, guided selling en personalisatie, op het gebied van prijzen, functies en de platforms waarop je verkoopt. Eerlijke, actuele vergelijkingen.",
  cmp_hub_title: "RevenueHunt vs de alternatieven: vergelijk quiztools",
  cmp_hub_desc: "Zie hoe RevenueHunt zich verhoudt tot Octane AI, Typeform, Zoovu, Nosto, Jebbit en Tolstoy op prijzen, functies en platforms voor productaanbevelingsquizzen.",
  gl_breadcrumb: "Woordenlijst",
  gl_eyebrow: "Woordenlijst",
  gl_reviewed: "Laatst herzien {date}",
  gl_with_rh_h2: "{term} met RevenueHunt",
  gl_cta_start: "begin gratis op Shopify",
  gl_cta_how: "zie hoe het werkt",
  gl_related_h2: "Gerelateerde artikelen",
  gl_more_h2: "Meer termen uit de woordenlijst",
  gl_cta_h2: "Breng het in de praktijk met een productaanbevelingsquiz.",
  gl_hub_eyebrow: "Woordenlijst",
  gl_hub_h1: "Woordenlijst quiz en personalisatie",
  gl_hub_sub: "Heldere definities van de termen achter productquizzen en e-commerce-personalisatie. Geen jargon, geen opvulling, alleen wat elke term betekent en waarom hij ertoe doet.",
  gl_hub_title: "Woordenlijst quiz & personalisatie",
  gl_hub_desc: "Heldere definities van de quiz- en personalisatietermen in e-commerce: conversational commerce, productontdekking, quiztrechters en meer.",
  gl_hub_terms_h2: "Termen",
  gl_hub_read: "Lees definitie",
  gl_hub_guides_h2: "Gidsen en tools",
  gl_hub_guides_sub: "Diepere gidsen over de bovenstaande onderwerpen, en een calculator om de kans voor je winkel in te schatten.",
  gl_hub_readmore: "Lees meer",
};

const sv: LongtailChrome = {
  faq_h2: "Vanliga frågor",
  cta_kicker: "De flesta shoppare lämnar för att de inte hittar rätt produkt",
  cta_h2: "Förvandla shoppare till självsäkra köpare med en produktrekommendationsquiz som driver försäljning.",
  cta_start_shopify: "kom igång gratis på Shopify",
  cta_start_woo: "kom igång gratis på WooCommerce",
  trial_note: "Gratisplan tillgänglig · 15 dagars gratis testperiod · 30 dagars pengarna-tillbaka-garanti",
  hub_brands_h2: "Se varför 20 000+ varumärken väljer RevenueHunt.",
  sol_breadcrumb: "Lösningar",
  sol_eyebrow: "Lösning",
  sol_cta_demo: "se en livedemo",
  sol_proof_brands: "varumärken",
  sol_proof_quizzes: "slutförda quiz",
  sol_proof_revenue: "handlarnas intäkter",
  sol_proof_reviews: "550+ recensioner",
  sol_quiztypes_h2: "Populära {name}-quiztyper",
  sol_quiztypes_sub: "Vanliga mönster som handlare bygger med RevenueHunt. Kombinera dem i ett och samma quiz.",
  sol_howhelps_h2: "Vad ett {name}-quiz gör för din butik",
  sol_seeitlive: "Se det live",
  sol_caps_h2: "Allt som ett RevenueHunt-quiz innehåller",
  sol_caps: [
    { title: "Gratis att börja", body: "En genuint gratis plan med 100 svar i månaden, på liveutiker. Betalplaner från $39/month." },
    { title: "AI Quiz Copilot", body: "Beskriv din butik så bygger Copilot ett komplett quiz, logik och produktkopplingar på ungefär 60 sekunder." },
    { title: "Katalogsynk i realtid", body: "Rekommenderar riktiga produkter och varianter från din livekatalog, automatiskt synkroniserade." },
    { title: "Obegränsade quiz & logik", body: "Bygg så många quiz du vill på varje plan, med obegränsad villkors- och förgreningslogik." },
    { title: "Klaviyo- & e-postsynk", body: "Svar och kundtaggar flödar till Klaviyo, Mailchimp, Omnisend, HubSpot med flera för segmentering." },
    { title: "Avhopps-analys", body: "Se avhoppen fråga för fråga så att du kan åtgärda friktion och återvinna förlorade svar." },
  ],
  sol_related_h2: "Relaterade lösningar & resurser",
  sol_more_industries: "Fler branscher",
  sol_more_quiztypes: "Fler quiztyper",
  sol_view: "Visa lösning",
  cmp_breadcrumb: "Jämför",
  cmp_eyebrow_prefix: "Jämförelse · RevenueHunt vs",
  cmp_cta_install: "installera på Shopify",
  cmp_cta_demo: "se en livedemo",
  cmp_table_h2: "RevenueHunt vs {name} i korthet",
  cmp_table_sub: "De funktioner som betyder mest för ett Shopify-produktquiz.",
  cmp_col_feature: "Funktion",
  cmp_yes: "Ja",
  cmp_no: "Nej",
  cmp_note: "Jämförelse baserad på offentligt tillgänglig information från varje leverantör per {date}. Priser och funktioner för {name} kan ha ändrats sedan dess, så kolla deras webbplats för det senaste.",
  cmp_why_h2: "Varför handlare väljer RevenueHunt framför {name}",
  cmp_bestfor_h2: "När {name} kan passa bättre",
  cmp_switch_h2: "Byta från {name}",
  cmp_cta_start: "kom igång gratis på Shopify",
  cmp_cta_book: "boka en demo",
  cmp_other_h2: "Jämför andra quizverktyg",
  cmp_see: "Se jämförelse",
  cmp_hub_eyebrow: "Jämförelser",
  cmp_hub_h1: "RevenueHunt mot alternativen",
  cmp_hub_sub: "Hur RevenueHunt står sig mot andra verktyg för produktquiz, guidad försäljning och personalisering, vad gäller priser, funktioner och plattformarna du säljer på. Ärliga och aktuella jämförelser.",
  cmp_hub_title: "RevenueHunt mot alternativen: jämför quizverktyg",
  cmp_hub_desc: "Se hur RevenueHunt står sig mot Octane AI, Typeform, Zoovu, Nosto, Jebbit och Tolstoy vad gäller priser, funktioner och plattformar för produktrekommendationsquiz.",
  gl_breadcrumb: "Ordlista",
  gl_eyebrow: "Ordlista",
  gl_reviewed: "Senast granskad {date}",
  gl_with_rh_h2: "{term} med RevenueHunt",
  gl_cta_start: "kom igång gratis på Shopify",
  gl_cta_how: "se hur det fungerar",
  gl_related_h2: "Relaterad läsning",
  gl_more_h2: "Fler ordlistetermer",
  gl_cta_h2: "Omsätt det i praktiken med en produktrekommendationsquiz.",
  gl_hub_eyebrow: "Ordlista",
  gl_hub_h1: "Ordlista för quiz och personalisering",
  gl_hub_sub: "Tydliga definitioner av termerna bakom produktquiz och personalisering inom e-handel. Inget krångligt språk, ingen utfyllnad, bara vad varje term betyder och varför den spelar roll.",
  gl_hub_title: "Ordlista för quiz & personalisering",
  gl_hub_desc: "Tydliga definitioner av quiz- och personaliseringstermerna inom e-handel: conversational commerce, produktupptäckt, quiztrattar och mer.",
  gl_hub_terms_h2: "Termer",
  gl_hub_read: "Läs definition",
  gl_hub_guides_h2: "Guider och verktyg",
  gl_hub_guides_sub: "Djupare guider om ämnena ovan, och en kalkylator för att uppskatta möjligheten för din butik.",
  gl_hub_readmore: "Läs mer",
};

const fi: LongtailChrome = {
  faq_h2: "Usein kysytyt kysymykset",
  cta_kicker: "Useimmat asiakkaat poistuvat, koska eivät löydä oikeaa tuotetta",
  cta_h2: "Muuta asiakkaat itsevarmoiksi ostajiksi tuotesuosittelukyselyllä, joka kasvattaa myyntiä.",
  cta_start_shopify: "aloita ilmaiseksi Shopifyssa",
  cta_start_woo: "aloita ilmaiseksi WooCommercessa",
  trial_note: "Ilmainen suunnitelma saatavilla · 15 päivän ilmainen kokeilu · 30 päivän rahat takaisin -takuu",
  hub_brands_h2: "Katso, miksi yli 20 000 brändiä valitsee RevenueHuntin.",
  sol_breadcrumb: "Ratkaisut",
  sol_eyebrow: "Ratkaisu",
  sol_cta_demo: "katso live-demo",
  sol_proof_brands: "brändiä",
  sol_proof_quizzes: "suoritettua kyselyä",
  sol_proof_revenue: "kauppiaiden liikevaihto",
  sol_proof_reviews: "yli 550 arvostelua",
  sol_quiztypes_h2: "Suositut {name}-kyselytyypit",
  sol_quiztypes_sub: "Yleisiä malleja, joita kauppiaat rakentavat RevenueHuntilla. Yhdistä ne yhteen kyselyyn.",
  sol_howhelps_h2: "Mitä {name}-kysely tekee kaupallesi",
  sol_seeitlive: "Katso livenä",
  sol_caps_h2: "Kaikki, mitä RevenueHunt-kysely sisältää",
  sol_caps: [
    { title: "Ilmainen aloittaa", body: "Aidosti ilmainen suunnitelma, jossa on 100 vastausta kuukaudessa, live-kaupoissa. Maksulliset suunnitelmat alkaen $39/month." },
    { title: "AI Quiz Copilot", body: "Kuvaile kauppasi, niin Copilot rakentaa täyden kyselyn, logiikan ja tuotekytkennät noin 60 sekunnissa." },
    { title: "Reaaliaikainen luettelosynkronointi", body: "Suosittelee oikeita tuotteita ja variantteja live-luettelostasi, pidettynä automaattisesti synkronoituna." },
    { title: "Rajattomat kyselyt & logiikka", body: "Rakenna niin monta kyselyä kuin haluat jokaisessa suunnitelmassa, rajattomalla ehdollisella ja haarautuvalla logiikalla." },
    { title: "Klaviyo- & sähköpostisynkronointi", body: "Vastaukset ja asiakastagit virtaavat Klaviyoon, Mailchimpiin, Omnisendiin, HubSpotiin ja muihin segmentointia varten." },
    { title: "Keskeytysanalytiikka", body: "Näe keskeytykset kysymys kysymykseltä, jotta voit korjata kitkan ja palauttaa menetetyt vastaukset." },
  ],
  sol_related_h2: "Liittyvät ratkaisut & resurssit",
  sol_more_industries: "Lisää toimialoja",
  sol_more_quiztypes: "Lisää kyselytyyppejä",
  sol_view: "Näytä ratkaisu",
  cmp_breadcrumb: "Vertaa",
  cmp_eyebrow_prefix: "Vertailu · RevenueHunt vs",
  cmp_cta_install: "asenna Shopifyyn",
  cmp_cta_demo: "katso live-demo",
  cmp_table_h2: "RevenueHunt vs {name} yhdellä silmäyksellä",
  cmp_table_sub: "Ominaisuudet, joilla on eniten merkitystä Shopify-tuotekyselyssä.",
  cmp_col_feature: "Ominaisuus",
  cmp_yes: "Kyllä",
  cmp_no: "Ei",
  cmp_note: "Vertailu perustuu kunkin toimittajan julkisesti saatavilla olevaan tietoon päivämäärällä {date}. {name}-hinnoittelu ja -ominaisuudet ovat voineet muuttua sen jälkeen, joten tarkista heidän sivustonsa uusimmat tiedot.",
  cmp_why_h2: "Miksi kauppiaat valitsevat RevenueHuntin {name}:n sijaan",
  cmp_bestfor_h2: "Milloin {name} voi olla parempi valinta",
  cmp_switch_h2: "Vaihtaminen {name}:sta",
  cmp_cta_start: "aloita ilmaiseksi Shopifyssa",
  cmp_cta_book: "varaa demo",
  cmp_other_h2: "Vertaa muita kyselytyökaluja",
  cmp_see: "Katso vertailu",
  cmp_hub_eyebrow: "Vertailut",
  cmp_hub_h1: "RevenueHunt vs vaihtoehdot",
  cmp_hub_sub: "Miten RevenueHunt pärjää muihin tuotekysely-, ohjatun myynnin ja personoinnin työkaluihin verrattuna hinnoittelussa, ominaisuuksissa ja alustoissa, joilla myyt. Rehellisiä ja ajan tasalla olevia vertailuja.",
  cmp_hub_title: "RevenueHunt vs vaihtoehdot: vertaa kyselytyökaluja",
  cmp_hub_desc: "Katso, miten RevenueHunt pärjää Octane AI:hin, Typeformiin, Zoovuun, Nostoon, Jebbitiin ja Tolstoyhin verrattuna hinnoittelussa, ominaisuuksissa ja alustoissa tuotesuosittelukyselyille.",
  gl_breadcrumb: "Sanasto",
  gl_eyebrow: "Sanasto",
  gl_reviewed: "Viimeksi tarkistettu {date}",
  gl_with_rh_h2: "{term} RevenueHuntin kanssa",
  gl_cta_start: "aloita ilmaiseksi Shopifyssa",
  gl_cta_how: "katso miten se toimii",
  gl_related_h2: "Aiheeseen liittyvää luettavaa",
  gl_more_h2: "Lisää sanaston termejä",
  gl_cta_h2: "Vie se käytäntöön tuotesuosittelukyselyllä.",
  gl_hub_eyebrow: "Sanasto",
  gl_hub_h1: "Kyselyn ja personoinnin sanasto",
  gl_hub_sub: "Selkeitä määritelmiä tuotekyselyjen ja verkkokaupan personoinnin takana oleville termeille. Ei ammattijargonia eikä täytettä, vain mitä kukin tarkoittaa ja miksi sillä on väliä.",
  gl_hub_title: "Kyselyn & personoinnin sanasto",
  gl_hub_desc: "Selkeitä määritelmiä verkkokaupan kysely- ja personointitermeille: conversational commerce, tuotteiden löytäminen, kyselysuppilot ja muut.",
  gl_hub_terms_h2: "Termit",
  gl_hub_read: "Lue määritelmä",
  gl_hub_guides_h2: "Oppaat ja työkalut",
  gl_hub_guides_sub: "Syvällisempiä oppaita yllä olevista aiheista, ja laskuri kauppasi mahdollisuuden mitoittamiseen.",
  gl_hub_readmore: "Lue lisää",
};

const pl: LongtailChrome = {
  faq_h2: "Najczęściej zadawane pytania",
  cta_kicker: "Większość kupujących rezygnuje, bo nie może znaleźć właściwego produktu",
  cta_h2: "Zamień kupujących w pewnych siebie klientów dzięki quizowi rekomendacji produktów, który napędza sprzedaż.",
  cta_start_shopify: "zacznij za darmo na Shopify",
  cta_start_woo: "zacznij za darmo na WooCommerce",
  trial_note: "Dostępny darmowy plan · 15 dni darmowego okresu próbnego · 30-dniowa gwarancja zwrotu pieniędzy",
  hub_brands_h2: "Zobacz, dlaczego ponad 20 000 marek wybiera RevenueHunt.",
  sol_breadcrumb: "Rozwiązania",
  sol_eyebrow: "Rozwiązanie",
  sol_cta_demo: "zobacz demo na żywo",
  sol_proof_brands: "marek",
  sol_proof_quizzes: "ukończonych quizów",
  sol_proof_revenue: "przychody sprzedawców",
  sol_proof_reviews: "ponad 550 recenzji",
  sol_quiztypes_h2: "Popularne typy quizów {name}",
  sol_quiztypes_sub: "Typowe schematy, które sprzedawcy tworzą z RevenueHunt. Łącz je w jednym quizie.",
  sol_howhelps_h2: "Co quiz {name} robi dla Twojego sklepu",
  sol_seeitlive: "Zobacz na żywo",
  sol_caps_h2: "Wszystko, co zawiera quiz RevenueHunt",
  sol_caps: [
    { title: "Darmowy start", body: "Naprawdę darmowy plan z 100 odpowiedziami miesięcznie, w działających sklepach. Plany płatne od $39/month." },
    { title: "AI Quiz Copilot", body: "Opisz swój sklep, a Copilot w około 60 sekund zbuduje pełny quiz, logikę i powiązania produktów." },
    { title: "Synchronizacja katalogu w czasie rzeczywistym", body: "Poleca prawdziwe produkty i warianty z Twojego katalogu na żywo, utrzymywane w synchronizacji automatycznie." },
    { title: "Nieograniczone quizy i logika", body: "Twórz tyle quizów, ile chcesz, w każdym planie, z nieograniczoną logiką warunkową i rozgałęzioną." },
    { title: "Synchronizacja z Klaviyo i e-mailem", body: "Odpowiedzi i tagi klientów trafiają do Klaviyo, Mailchimp, Omnisend, HubSpot i innych, aby umożliwić segmentację." },
    { title: "Analityka porzuceń", body: "Zobacz porzucenia pytanie po pytaniu, aby usunąć tarcia i odzyskać utracone odpowiedzi." },
  ],
  sol_related_h2: "Powiązane rozwiązania i zasoby",
  sol_more_industries: "Więcej branż",
  sol_more_quiztypes: "Więcej typów quizów",
  sol_view: "Zobacz rozwiązanie",
  cmp_breadcrumb: "Porównaj",
  cmp_eyebrow_prefix: "Porównanie · RevenueHunt vs",
  cmp_cta_install: "zainstaluj na Shopify",
  cmp_cta_demo: "zobacz demo na żywo",
  cmp_table_h2: "RevenueHunt vs {name} w skrócie",
  cmp_table_sub: "Funkcje, które mają największe znaczenie dla quizu produktowego na Shopify.",
  cmp_col_feature: "Funkcja",
  cmp_yes: "Tak",
  cmp_no: "Nie",
  cmp_note: "Porównanie oparte na publicznie dostępnych informacjach każdego dostawcy na dzień {date}. Ceny i funkcje {name} mogły się od tego czasu zmienić, więc sprawdź ich stronę, aby poznać najnowsze informacje.",
  cmp_why_h2: "Dlaczego sprzedawcy wybierają RevenueHunt zamiast {name}",
  cmp_bestfor_h2: "Kiedy {name} może lepiej pasować",
  cmp_switch_h2: "Przejście z {name}",
  cmp_cta_start: "zacznij za darmo na Shopify",
  cmp_cta_book: "zarezerwuj demo",
  cmp_other_h2: "Porównaj inne narzędzia do quizów",
  cmp_see: "Zobacz porównanie",
  cmp_hub_eyebrow: "Porównania",
  cmp_hub_h1: "RevenueHunt kontra alternatywy",
  cmp_hub_sub: "Jak RevenueHunt wypada na tle innych narzędzi do quizów produktowych, sprzedaży kierowanej i personalizacji, pod względem cen, funkcji i platform, na których sprzedajesz. Uczciwe, aktualne porównania.",
  cmp_hub_title: "RevenueHunt kontra alternatywy: porównaj narzędzia do quizów",
  cmp_hub_desc: "Zobacz, jak RevenueHunt wypada na tle Octane AI, Typeform, Zoovu, Nosto, Jebbit i Tolstoy pod względem cen, funkcji i platform dla quizów rekomendacji produktów.",
  gl_breadcrumb: "Słownik",
  gl_eyebrow: "Słownik",
  gl_reviewed: "Ostatnio sprawdzono {date}",
  gl_with_rh_h2: "{term} z RevenueHunt",
  gl_cta_start: "zacznij za darmo na Shopify",
  gl_cta_how: "zobacz, jak to działa",
  gl_related_h2: "Powiązane lektury",
  gl_more_h2: "Więcej terminów ze słownika",
  gl_cta_h2: "Wprowadź to w życie dzięki quizowi rekomendacji produktów.",
  gl_hub_eyebrow: "Słownik",
  gl_hub_h1: "Słownik quizu i personalizacji",
  gl_hub_sub: "Jasne definicje terminów stojących za quizami produktowymi i personalizacją w e-commerce. Bez żargonu i lania wody, tylko co każdy oznacza i dlaczego ma znaczenie.",
  gl_hub_title: "Słownik quizu i personalizacji",
  gl_hub_desc: "Jasne definicje terminów z zakresu quizów i personalizacji w e-commerce: handel konwersacyjny, odkrywanie produktów, lejki quizowe i więcej.",
  gl_hub_terms_h2: "Terminy",
  gl_hub_read: "Przeczytaj definicję",
  gl_hub_guides_h2: "Przewodniki i narzędzia",
  gl_hub_guides_sub: "Głębsze przewodniki po powyższych tematach oraz kalkulator do oszacowania szansy dla Twojego sklepu.",
  gl_hub_readmore: "Czytaj więcej",
};

const cs: LongtailChrome = {
  faq_h2: "Časté dotazy",
  cta_kicker: "Většina nakupujících odejde, protože nemůže najít ten správný produkt",
  cta_h2: "Proměň nakupující v sebejisté kupce s kvízem s doporučením produktů, který žene prodeje nahoru.",
  cta_start_shopify: "začni zdarma na Shopify",
  cta_start_woo: "začni zdarma na WooCommerce",
  trial_note: "Bezplatný plán k dispozici · 15denní zkušební verze zdarma · 30denní záruka vrácení peněz",
  hub_brands_h2: "Podívej se, proč si RevenueHunt vybírá více než 20 000 značek.",
  sol_breadcrumb: "Řešení",
  sol_eyebrow: "Řešení",
  sol_cta_demo: "podívej se na živé demo",
  sol_proof_brands: "značek",
  sol_proof_quizzes: "dokončených kvízů",
  sol_proof_revenue: "tržby obchodníků",
  sol_proof_reviews: "více než 550 recenzí",
  sol_quiztypes_h2: "Oblíbené typy kvízů {name}",
  sol_quiztypes_sub: "Běžné vzory, které obchodníci staví s RevenueHunt. Kombinuj je v jednom kvízu.",
  sol_howhelps_h2: "Co kvíz {name} udělá pro tvůj obchod",
  sol_seeitlive: "Podívej se naživo",
  sol_caps_h2: "Vše, co kvíz RevenueHunt zahrnuje",
  sol_caps: [
    { title: "Zdarma na start", body: "Opravdu bezplatný plán se 100 odpověďmi měsíčně, v živých obchodech. Placené plány od $39/month." },
    { title: "AI Quiz Copilot", body: "Popiš svůj obchod a Copilot za zhruba 60 sekund sestaví kompletní kvíz, logiku a propojení produktů." },
    { title: "Synchronizace katalogu v reálném čase", body: "Doporučuje skutečné produkty a varianty z tvého živého katalogu, automaticky udržované v synchronizaci." },
    { title: "Neomezené kvízy a logika", body: "Vytvoř tolik kvízů, kolik chceš, v každém plánu, s neomezenou podmíněnou a větvící logikou." },
    { title: "Synchronizace s Klaviyo a e-mailem", body: "Odpovědi a štítky zákazníků putují do Klaviyo, Mailchimp, Omnisend, HubSpot a dalších pro segmentaci." },
    { title: "Analytika odchodů", body: "Sleduj odchody otázku po otázce, abys odstranil tření a získal zpět ztracené odpovědi." },
  ],
  sol_related_h2: "Související řešení a zdroje",
  sol_more_industries: "Další odvětví",
  sol_more_quiztypes: "Další typy kvízů",
  sol_view: "Zobrazit řešení",
  cmp_breadcrumb: "Porovnat",
  cmp_eyebrow_prefix: "Porovnání · RevenueHunt vs",
  cmp_cta_install: "nainstaluj na Shopify",
  cmp_cta_demo: "podívej se na živé demo",
  cmp_table_h2: "RevenueHunt vs {name} ve zkratce",
  cmp_table_sub: "Funkce, které jsou pro produktový kvíz na Shopify nejdůležitější.",
  cmp_col_feature: "Funkce",
  cmp_yes: "Ano",
  cmp_no: "Ne",
  cmp_note: "Porovnání založené na veřejně dostupných informacích od každého poskytovatele k datu {date}. Ceny a funkce {name} se od té doby mohly změnit, takže si na jejich webu ověř nejnovější informace.",
  cmp_why_h2: "Proč si obchodníci vybírají RevenueHunt místo {name}",
  cmp_bestfor_h2: "Kdy se {name} může hodit lépe",
  cmp_switch_h2: "Přechod z {name}",
  cmp_cta_start: "začni zdarma na Shopify",
  cmp_cta_book: "rezervuj si demo",
  cmp_other_h2: "Porovnej další nástroje pro kvízy",
  cmp_see: "Zobrazit porovnání",
  cmp_hub_eyebrow: "Porovnání",
  cmp_hub_h1: "RevenueHunt versus alternativy",
  cmp_hub_sub: "Jak si RevenueHunt stojí proti dalším nástrojům pro produktové kvízy, řízený prodej a personalizaci, co se týče cen, funkcí a platforem, na kterých prodáváš. Poctivá a aktuální porovnání.",
  cmp_hub_title: "RevenueHunt versus alternativy: porovnej nástroje pro kvízy",
  cmp_hub_desc: "Podívej se, jak si RevenueHunt stojí proti Octane AI, Typeform, Zoovu, Nosto, Jebbit a Tolstoy v cenách, funkcích a platformách pro kvízy s doporučením produktů.",
  gl_breadcrumb: "Slovníček",
  gl_eyebrow: "Slovníček",
  gl_reviewed: "Naposledy zkontrolováno {date}",
  gl_with_rh_h2: "{term} s RevenueHunt",
  gl_cta_start: "začni zdarma na Shopify",
  gl_cta_how: "podívej se, jak to funguje",
  gl_related_h2: "Související čtení",
  gl_more_h2: "Další pojmy ze slovníčku",
  gl_cta_h2: "Uveď to do praxe s kvízem s doporučením produktů.",
  gl_hub_eyebrow: "Slovníček",
  gl_hub_h1: "Slovníček kvízů a personalizace",
  gl_hub_sub: "Srozumitelné definice pojmů, které stojí za produktovými kvízy a personalizací v e-commerce. Žádný žargon, žádná vata, jen co každý pojem znamená a proč na něm záleží.",
  gl_hub_title: "Slovníček kvízů a personalizace",
  gl_hub_desc: "Srozumitelné definice pojmů kvízů a personalizace v e-commerce: konverzační obchod, objevování produktů, kvízové trychtýře a další.",
  gl_hub_terms_h2: "Pojmy",
  gl_hub_read: "Přečíst definici",
  gl_hub_guides_h2: "Průvodci a nástroje",
  gl_hub_guides_sub: "Hlubší průvodci k tématům výše a kalkulačka pro odhad příležitosti tvého obchodu.",
  gl_hub_readmore: "Číst více",
};

const ar: LongtailChrome = {
  faq_h2: "الأسئلة الشائعة",
  cta_kicker: "معظم المتسوقين يغادرون لأنهم لا يجدون المنتج المناسب",
  cta_h2: "حوّل المتسوقين إلى مشترين واثقين عبر اختبار التوصية بالمنتجات يزيد المبيعات.",
  cta_start_shopify: "ابدأ مجانًا على Shopify",
  cta_start_woo: "ابدأ مجانًا على WooCommerce",
  trial_note: "خطة مجانية متاحة · تجربة مجانية لمدة 15 يومًا · ضمان استرداد المال خلال 30 يومًا",
  hub_brands_h2: "اكتشف لماذا تختار أكثر من 20,000 علامة تجارية RevenueHunt.",
  sol_breadcrumb: "الحلول",
  sol_eyebrow: "الحل",
  sol_cta_demo: "شاهد عرضًا توضيحيًا مباشرًا",
  sol_proof_brands: "علامات تجارية",
  sol_proof_quizzes: "اختبارات مكتملة",
  sol_proof_revenue: "إيرادات التجار",
  sol_proof_reviews: "أكثر من 550 مراجعة",
  sol_quiztypes_h2: "أنواع اختبارات {name} الشائعة",
  sol_quiztypes_sub: "أنماط شائعة ينشئها التجار باستخدام RevenueHunt. اجمع بينها في اختبار واحد.",
  sol_howhelps_h2: "ما يقدمه اختبار {name} لمتجرك",
  sol_seeitlive: "شاهده مباشرة",
  sol_caps_h2: "كل ما يتضمنه اختبار RevenueHunt",
  sol_caps: [
    { title: "مجاني للبدء", body: "خطة مجانية حقًا مع 100 رد شهريًا، على متاجر حقيقية. خطط مدفوعة ابتداءً من $39/month." },
    { title: "AI Quiz Copilot", body: "صِف متجرك ويبني Copilot اختبارًا كاملًا، مع منطقه وربط المنتجات، في نحو 60 ثانية." },
    { title: "مزامنة الكتالوج في الوقت الفعلي", body: "يوصي بمنتجات وتنويعات حقيقية من كتالوجك المباشر، تُحفظ متزامنة تلقائيًا." },
    { title: "اختبارات ومنطق غير محدودة", body: "أنشئ ما تشاء من الاختبارات في أي خطة، مع منطق شرطي وتفرعي غير محدود." },
    { title: "مزامنة مع Klaviyo والبريد الإلكتروني", body: "تتدفق الردود وعلامات العملاء إلى Klaviyo وMailchimp وOmnisend وHubSpot وغيرها للتقسيم." },
    { title: "تحليلات التسرب", body: "اطّلع على التسرب سؤالًا بسؤال لتصلح نقاط الاحتكاك وتستعيد الردود المفقودة." },
  ],
  sol_related_h2: "الحلول والموارد ذات الصلة",
  sol_more_industries: "المزيد من القطاعات",
  sol_more_quiztypes: "المزيد من أنواع الاختبارات",
  sol_view: "عرض الحل",
  cmp_breadcrumb: "قارن",
  cmp_eyebrow_prefix: "مقارنة · RevenueHunt مقابل",
  cmp_cta_install: "ثبّت على Shopify",
  cmp_cta_demo: "شاهد عرضًا توضيحيًا مباشرًا",
  cmp_table_h2: "RevenueHunt مقابل {name} في لمحة",
  cmp_table_sub: "الميزات الأكثر أهمية لاختبار منتجات على Shopify.",
  cmp_col_feature: "الميزة",
  cmp_yes: "نعم",
  cmp_no: "لا",
  cmp_note: "مقارنة مبنية على معلومات متاحة للعموم من كل مزوّد بتاريخ {date}. قد تكون أسعار وميزات {name} تغيّرت منذ ذلك الحين، لذا راجع موقعهم لأحدث المعلومات.",
  cmp_why_h2: "لماذا يختار التجار RevenueHunt على {name}",
  cmp_bestfor_h2: "متى قد يكون {name} الخيار الأنسب",
  cmp_switch_h2: "الانتقال من {name}",
  cmp_cta_start: "ابدأ مجانًا على Shopify",
  cmp_cta_book: "احجز عرضًا توضيحيًا",
  cmp_other_h2: "قارن أدوات اختبار أخرى",
  cmp_see: "عرض المقارنة",
  cmp_hub_eyebrow: "المقارنات",
  cmp_hub_h1: "RevenueHunt مقابل البدائل",
  cmp_hub_sub: "كيف يقارَن RevenueHunt بأدوات اختبار المنتجات والبيع الموجّه والتخصيص الأخرى، من حيث الأسعار والميزات والمنصات التي تبيع عليها. مقارنات صادقة ومحدّثة.",
  cmp_hub_title: "RevenueHunt مقابل البدائل: قارن أدوات الاختبار",
  cmp_hub_desc: "اكتشف كيف يقارَن RevenueHunt بـ Octane AI وTypeform وZoovu وNosto وJebbit وTolstoy من حيث الأسعار والميزات والمنصات لاختبارات التوصية بالمنتجات.",
  gl_breadcrumb: "المسرد",
  gl_eyebrow: "المسرد",
  gl_reviewed: "آخر مراجعة {date}",
  gl_with_rh_h2: "{term} مع RevenueHunt",
  gl_cta_start: "ابدأ مجانًا على Shopify",
  gl_cta_how: "شاهد كيف يعمل",
  gl_related_h2: "قراءات ذات صلة",
  gl_more_h2: "المزيد من مصطلحات المسرد",
  gl_cta_h2: "طبّقه عمليًا عبر اختبار التوصية بالمنتجات.",
  gl_hub_eyebrow: "المسرد",
  gl_hub_h1: "مسرد الاختبار والتخصيص",
  gl_hub_sub: "تعريفات واضحة للمصطلحات وراء اختبارات المنتجات والتخصيص في التجارة الإلكترونية. بلا مصطلحات معقّدة أو حشو، فقط ما يعنيه كل مصطلح ولماذا يهم.",
  gl_hub_title: "مسرد الاختبار والتخصيص",
  gl_hub_desc: "تعريفات واضحة لمصطلحات الاختبار والتخصيص في التجارة الإلكترونية: التجارة الحوارية، اكتشاف المنتجات، مسارات الاختبار والمزيد.",
  gl_hub_terms_h2: "المصطلحات",
  gl_hub_read: "اقرأ التعريف",
  gl_hub_guides_h2: "الأدلة والأدوات",
  gl_hub_guides_sub: "أدلة أعمق حول المواضيع أعلاه، وحاسبة لتقدير حجم الفرصة لمتجرك.",
  gl_hub_readmore: "اقرأ المزيد",
};

const he: LongtailChrome = {
  faq_h2: "שאלות נפוצות",
  cta_kicker: "רוב הקונים עוזבים כי הם לא מוצאים את המוצר הנכון",
  cta_h2: "הפכו את הקונים לרוכשים בטוחים בעזרת חידון המלצת מוצרים שמגדיל מכירות.",
  cta_start_shopify: "התחילו בחינם ב-Shopify",
  cta_start_woo: "התחילו בחינם ב-WooCommerce",
  trial_note: "תוכנית חינמית זמינה · ניסיון חינם ל-15 יום · החזר כספי תוך 30 יום",
  hub_brands_h2: "גלו למה יותר מ-20,000 מותגים בוחרים ב-RevenueHunt.",
  sol_breadcrumb: "פתרונות",
  sol_eyebrow: "פתרון",
  sol_cta_demo: "צפו בהדגמה חיה",
  sol_proof_brands: "מותגים",
  sol_proof_quizzes: "חידונים שהושלמו",
  sol_proof_revenue: "הכנסות סוחרים",
  sol_proof_reviews: "יותר מ-550 ביקורות",
  sol_quiztypes_h2: "סוגי חידוני {name} פופולריים",
  sol_quiztypes_sub: "תבניות נפוצות שסוחרים בונים עם RevenueHunt. שלבו אותן בחידון אחד.",
  sol_howhelps_h2: "מה חידון {name} עושה לחנות שלכם",
  sol_seeitlive: "ראו את זה בשידור חי",
  sol_caps_h2: "כל מה שחידון RevenueHunt כולל",
  sol_caps: [
    { title: "חינם להתחלה", body: "תוכנית באמת חינמית עם 100 תשובות בחודש, בחנויות חיות. תוכניות בתשלום החל מ-$39/month." },
    { title: "AI Quiz Copilot", body: "תארו את החנות שלכם וה-Copilot בונה חידון מלא, עם הלוגיקה ושיוך המוצרים, בכ-60 שניות." },
    { title: "סנכרון קטלוג בזמן אמת", body: "ממליץ על מוצרים ווריאציות אמיתיים מהקטלוג החי שלכם, מסונכרנים אוטומטית." },
    { title: "חידונים ולוגיקה ללא הגבלה", body: "בנו כמה חידונים שתרצו בכל תוכנית, עם לוגיקה מותנית והסתעפות ללא הגבלה." },
    { title: "סנכרון עם Klaviyo ואימייל", body: "התשובות ותגיות הלקוח זורמות ל-Klaviyo, Mailchimp, Omnisend, HubSpot ועוד לצורך פילוח." },
    { title: "ניתוח נטישה", body: "ראו את הנטישה שאלה אחר שאלה כדי לתקן חיכוך ולשחזר תשובות אבודות." },
  ],
  sol_related_h2: "פתרונות ומשאבים קשורים",
  sol_more_industries: "עוד תחומים",
  sol_more_quiztypes: "עוד סוגי חידונים",
  sol_view: "צפו בפתרון",
  cmp_breadcrumb: "השוואה",
  cmp_eyebrow_prefix: "השוואה · RevenueHunt מול",
  cmp_cta_install: "התקינו ב-Shopify",
  cmp_cta_demo: "צפו בהדגמה חיה",
  cmp_table_h2: "RevenueHunt מול {name} במבט מהיר",
  cmp_table_sub: "הפיצ'רים שהכי חשובים לחידון מוצרים ב-Shopify.",
  cmp_col_feature: "פיצ'ר",
  cmp_yes: "כן",
  cmp_no: "לא",
  cmp_note: "השוואה המבוססת על מידע זמין לציבור מכל ספק נכון ל-{date}. המחירים והפיצ'רים של {name} עשויים להשתנות מאז, אז בדקו את האתר שלהם למידע העדכני ביותר.",
  cmp_why_h2: "למה סוחרים בוחרים ב-RevenueHunt על פני {name}",
  cmp_bestfor_h2: "מתי {name} עשוי להתאים יותר",
  cmp_switch_h2: "מעבר מ-{name}",
  cmp_cta_start: "התחילו בחינם ב-Shopify",
  cmp_cta_book: "קבעו הדגמה",
  cmp_other_h2: "השוו כלי חידונים אחרים",
  cmp_see: "ראו השוואה",
  cmp_hub_eyebrow: "השוואות",
  cmp_hub_h1: "RevenueHunt מול החלופות",
  cmp_hub_sub: "איך RevenueHunt מתמודד מול כלים אחרים לחידוני מוצרים, מכירה מודרכת והתאמה אישית, מבחינת מחירים, פיצ'רים והפלטפורמות שאתם מוכרים בהן. השוואות כנות ומעודכנות.",
  cmp_hub_title: "RevenueHunt מול החלופות: השוו כלי חידונים",
  cmp_hub_desc: "ראו איך RevenueHunt מתמודד מול Octane AI, Typeform, Zoovu, Nosto, Jebbit ו-Tolstoy מבחינת מחירים, פיצ'רים ופלטפורמות לחידוני המלצת מוצרים.",
  gl_breadcrumb: "מילון מונחים",
  gl_eyebrow: "מילון מונחים",
  gl_reviewed: "נבדק לאחרונה {date}",
  gl_with_rh_h2: "{term} עם RevenueHunt",
  gl_cta_start: "התחילו בחינם ב-Shopify",
  gl_cta_how: "ראו איך זה עובד",
  gl_related_h2: "קריאה קשורה",
  gl_more_h2: "עוד מונחים במילון",
  gl_cta_h2: "יישמו את זה בפועל עם חידון המלצת מוצרים.",
  gl_hub_eyebrow: "מילון מונחים",
  gl_hub_h1: "מילון מונחים לחידונים והתאמה אישית",
  gl_hub_sub: "הגדרות ברורות למונחים שמאחורי חידוני מוצרים והתאמה אישית במסחר אלקטרוני. בלי ז'רגון, בלי מילוי, רק מה כל מונח אומר ולמה הוא חשוב.",
  gl_hub_title: "מילון מונחים לחידונים והתאמה אישית",
  gl_hub_desc: "הגדרות ברורות למונחי חידונים והתאמה אישית במסחר אלקטרוני: מסחר שיחתי, גילוי מוצרים, משפכי חידונים ועוד.",
  gl_hub_terms_h2: "מונחים",
  gl_hub_read: "קראו הגדרה",
  gl_hub_guides_h2: "מדריכים וכלים",
  gl_hub_guides_sub: "מדריכים מעמיקים יותר על הנושאים שלמעלה, ומחשבון להערכת ההזדמנות לחנות שלכם.",
  gl_hub_readmore: "קראו עוד",
};

// Phase: es/fr/de/pt/it/nl/sv/fi/pl/cs are filled in by a translator pass. Until
// then `LT` falls back to English for any missing locale so the site still builds.
const FILLED: Partial<Record<Lang, LongtailChrome>> = { en, es, fr, de, pt, it, nl, sv, fi, pl, cs, ar, he };

export const LT: Record<Lang, LongtailChrome> = {
  en,
  es: FILLED.es ?? en,
  fr: FILLED.fr ?? en,
  de: FILLED.de ?? en,
  pt: FILLED.pt ?? en,
  it: FILLED.it ?? en,
  nl: FILLED.nl ?? en,
  sv: FILLED.sv ?? en,
  fi: FILLED.fi ?? en,
  pl: FILLED.pl ?? en,
  cs: FILLED.cs ?? en,
  ar: FILLED.ar ?? en,
  he: FILLED.he ?? en,
};

/** Fill {name}/{category}/{date}/{term} placeholders. */
export function fillLT(tpl: string, vars: Record<string, string>): string {
  return tpl.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}
