import type { Lang } from "./i18n";

export interface PlanFeature {
  text: string;
  link?: { label: string; href: string };
  /** Plus icon instead of check (used for Premium's "+ Larger plans" line). */
  plus?: boolean;
}

export interface Plan {
  name: string;
  /** Big price. "FREE" for the free plan, otherwise the numeric amount. */
  price: string;
  /** Yearly billing price (per-month equivalent - 20% off monthly). */
  priceYearly?: string;
  /** Small text adjacent to the price (e.g. "USD/mo."). Omit on Free. */
  priceSuffix?: string;
  /** Asterisked sub-price line. */
  priceNote: string;
  /** Asterisked sub-price line when yearly billing is selected. */
  priceNoteYearly?: string;
  tagline: string;
  features: PlanFeature[];
}

export const PLANS: Plan[] = [
  {
    name: "Free Plan",
    price: "FREE",
    priceNote: "* Yes, really!",
    tagline: "Perfect for new brands.",
    features: [
      { text: "100 quiz responses/mo." },
      { text: "Email support" },
      { text: "Create unlimited quizzes" },
      { text: "Custom quiz design" },
      { text: "Conditional logic" },
      { text: "Advanced quiz analytics" },
      { text: "Shopify Markets" },
      { text: "Export quiz leads to CSV" },
      { text: "GDPR & CCPA compliant" },
    ],
  },
  {
    name: "Basic Plan",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mo.",
    priceNote: "* Billed monthly",
    priceNoteYearly: "* Billed yearly",
    tagline: "For growing mid-tier stores.",
    features: [
      { text: "500 quiz responses/mo." },
      { text: "Free features +" },
      { text: "Live chat support" },
      { text: "Custom HTML, CSS & JS" },
      { text: "GA4 & Meta Pixel" },
      { text: "Webhooks & Zapier" },
      { text: "Klaviyo, Omnisend &", link: { label: "more integrations", href: "/integrations/" } },
    ],
  },
  {
    name: "Pro Plan",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mo.",
    priceNote: "* Billed monthly",
    priceNoteYearly: "* Billed yearly",
    tagline: "For brands ready to scale.",
    features: [
      { text: "1,000 quiz responses/mo." },
      { text: "Basic features +" },
      { text: "Video call support" },
      { text: "Account manager" },
    ],
  },
  {
    name: "Premium Plan",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mo.",
    priceNote: "* Billed monthly",
    priceNoteYearly: "* Billed yearly",
    tagline: "Established, multi-market brands.",
    features: [
      { text: "2,500 quiz responses/mo." },
      { text: "Pro features +" },
      { text: "Quarterly strategy review" },
      { text: "Larger plans -", link: { label: "view", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_ES: Plan[] = [
  {
    name: "Plan gratuito",
    price: "FREE",
    priceNote: "* ¡Sí, en serio!",
    tagline: "Perfecto para marcas nuevas.",
    features: [
      { text: "100 respuestas de quiz/mes" },
      { text: "Soporte por email" },
      { text: "Crea quizzes ilimitados" },
      { text: "Diseño de quiz personalizado" },
      { text: "Lógica condicional" },
      { text: "Analítica avanzada de quiz" },
      { text: "Shopify Markets" },
      { text: "Exporta leads del quiz a CSV" },
      { text: "Cumple GDPR y CCPA" },
    ],
  },
  {
    name: "Plan básico",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mes",
    priceNote: "* Facturación mensual",
    priceNoteYearly: "* Facturación anual",
    tagline: "Para tiendas medianas en crecimiento.",
    features: [
      { text: "500 respuestas de quiz/mes" },
      { text: "Funciones del gratuito +" },
      { text: "Soporte por chat en vivo" },
      { text: "HTML, CSS y JS personalizados" },
      { text: "GA4 y Meta Pixel" },
      { text: "Webhooks y Zapier" },
      { text: "Klaviyo, Omnisend y", link: { label: "más integraciones", href: "/integrations/" } },
    ],
  },
  {
    name: "Plan Pro",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mes",
    priceNote: "* Facturación mensual",
    priceNoteYearly: "* Facturación anual",
    tagline: "Para marcas listas para escalar.",
    features: [
      { text: "1.000 respuestas de quiz/mes" },
      { text: "Funciones del básico +" },
      { text: "Soporte por videollamada" },
      { text: "Gestor de cuenta" },
    ],
  },
  {
    name: "Plan Premium",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mes",
    priceNote: "* Facturación mensual",
    priceNoteYearly: "* Facturación anual",
    tagline: "Marcas consolidadas y multimercado.",
    features: [
      { text: "2.500 respuestas de quiz/mes" },
      { text: "Funciones del Pro +" },
      { text: "Revisión de estrategia trimestral" },
      { text: "Planes mayores -", link: { label: "ver", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_FR: Plan[] = [
  {
    name: "Offre gratuite",
    price: "FREE",
    priceNote: "* Oui, vraiment !",
    tagline: "Parfait pour les nouvelles marques.",
    features: [
      { text: "100 réponses de quiz/mois" },
      { text: "Support par email" },
      { text: "Créez des quiz illimités" },
      { text: "Design de quiz personnalisé" },
      { text: "Logique conditionnelle" },
      { text: "Analyse avancée des quiz" },
      { text: "Shopify Markets" },
      { text: "Exportez les leads du quiz en CSV" },
      { text: "Conforme RGPD et CCPA" },
    ],
  },
  {
    name: "Offre Basic",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mois",
    priceNote: "* Facturation mensuelle",
    priceNoteYearly: "* Facturation annuelle",
    tagline: "Pour les boutiques intermédiaires en croissance.",
    features: [
      { text: "500 réponses de quiz/mois" },
      { text: "Fonctionnalités de l'offre gratuite +" },
      { text: "Support par chat en direct" },
      { text: "HTML, CSS et JS personnalisés" },
      { text: "GA4 et Meta Pixel" },
      { text: "Webhooks et Zapier" },
      { text: "Klaviyo, Omnisend et", link: { label: "plus d'intégrations", href: "/integrations/" } },
    ],
  },
  {
    name: "Offre Pro",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mois",
    priceNote: "* Facturation mensuelle",
    priceNoteYearly: "* Facturation annuelle",
    tagline: "Pour les marques prêtes à passer à l'échelle.",
    features: [
      { text: "1 000 réponses de quiz/mois" },
      { text: "Fonctionnalités de l'offre Basic +" },
      { text: "Support par appel vidéo" },
      { text: "Gestionnaire de compte" },
    ],
  },
  {
    name: "Offre Premium",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mois",
    priceNote: "* Facturation mensuelle",
    priceNoteYearly: "* Facturation annuelle",
    tagline: "Marques établies et multi-marchés.",
    features: [
      { text: "2 500 réponses de quiz/mois" },
      { text: "Fonctionnalités de l'offre Pro +" },
      { text: "Revue de stratégie trimestrielle" },
      { text: "Offres plus larges -", link: { label: "voir", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_DE: Plan[] = [
  {
    name: "Kostenloser Plan",
    price: "FREE",
    priceNote: "* Ja, wirklich!",
    tagline: "Perfekt für neue Marken.",
    features: [
      { text: "100 Quiz-Antworten/Mon." },
      { text: "E-Mail-Support" },
      { text: "Unbegrenzt Quizze erstellen" },
      { text: "Individuelles Quiz-Design" },
      { text: "Bedingte Logik" },
      { text: "Erweiterte Quiz-Analytik" },
      { text: "Shopify Markets" },
      { text: "Quiz-Leads als CSV exportieren" },
      { text: "DSGVO- & CCPA-konform" },
    ],
  },
  {
    name: "Basic-Plan",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/Mon.",
    priceNote: "* Monatliche Abrechnung",
    priceNoteYearly: "* Jährliche Abrechnung",
    tagline: "Für wachsende Stores im mittleren Segment.",
    features: [
      { text: "500 Quiz-Antworten/Mon." },
      { text: "Funktionen des Kostenlosen +" },
      { text: "Live-Chat-Support" },
      { text: "Eigenes HTML, CSS & JS" },
      { text: "GA4 & Meta Pixel" },
      { text: "Webhooks & Zapier" },
      { text: "Klaviyo, Omnisend &", link: { label: "weitere Integrationen", href: "/integrations/" } },
    ],
  },
  {
    name: "Pro-Plan",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/Mon.",
    priceNote: "* Monatliche Abrechnung",
    priceNoteYearly: "* Jährliche Abrechnung",
    tagline: "Für Marken, die bereit sind zu skalieren.",
    features: [
      { text: "1.000 Quiz-Antworten/Mon." },
      { text: "Funktionen des Basic +" },
      { text: "Support per Videocall" },
      { text: "Account-Manager" },
    ],
  },
  {
    name: "Premium-Plan",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/Mon.",
    priceNote: "* Monatliche Abrechnung",
    priceNoteYearly: "* Jährliche Abrechnung",
    tagline: "Etablierte Marken mit mehreren Märkten.",
    features: [
      { text: "2.500 Quiz-Antworten/Mon." },
      { text: "Funktionen des Pro +" },
      { text: "Vierteljährliche Strategie-Review" },
      { text: "Größere Pläne -", link: { label: "ansehen", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_PT: Plan[] = [
  {
    name: "Plano gratuito",
    price: "FREE",
    priceNote: "* Sim, a sério!",
    tagline: "Perfeito para marcas novas.",
    features: [
      { text: "100 respostas de quiz/mês" },
      { text: "Suporte por email" },
      { text: "Cria quizzes ilimitados" },
      { text: "Design de quiz personalizado" },
      { text: "Lógica condicional" },
      { text: "Analítica avançada de quiz" },
      { text: "Shopify Markets" },
      { text: "Exporta leads do quiz para CSV" },
      { text: "Conforme RGPD e CCPA" },
    ],
  },
  {
    name: "Plano básico",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mês",
    priceNote: "* Faturação mensal",
    priceNoteYearly: "* Faturação anual",
    tagline: "Para lojas intermédias em crescimento.",
    features: [
      { text: "500 respostas de quiz/mês" },
      { text: "Funcionalidades do gratuito +" },
      { text: "Suporte por chat ao vivo" },
      { text: "HTML, CSS e JS personalizados" },
      { text: "GA4 e Meta Pixel" },
      { text: "Webhooks e Zapier" },
      { text: "Klaviyo, Omnisend e", link: { label: "mais integrações", href: "/integrations/" } },
    ],
  },
  {
    name: "Plano Pro",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mês",
    priceNote: "* Faturação mensal",
    priceNoteYearly: "* Faturação anual",
    tagline: "Para marcas prontas para escalar.",
    features: [
      { text: "1.000 respostas de quiz/mês" },
      { text: "Funcionalidades do básico +" },
      { text: "Suporte por videochamada" },
      { text: "Gestor de conta" },
    ],
  },
  {
    name: "Plano Premium",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mês",
    priceNote: "* Faturação mensal",
    priceNoteYearly: "* Faturação anual",
    tagline: "Marcas consolidadas e multimercado.",
    features: [
      { text: "2.500 respostas de quiz/mês" },
      { text: "Funcionalidades do Pro +" },
      { text: "Revisão de estratégia trimestral" },
      { text: "Planos maiores -", link: { label: "ver", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_IT: Plan[] = [
  {
    name: "Piano gratuito",
    price: "FREE",
    priceNote: "* Sì, davvero!",
    tagline: "Perfetto per i nuovi brand.",
    features: [
      { text: "100 risposte al quiz/mese" },
      { text: "Supporto via email" },
      { text: "Crea quiz illimitati" },
      { text: "Design del quiz personalizzato" },
      { text: "Logica condizionale" },
      { text: "Analisi avanzata dei quiz" },
      { text: "Shopify Markets" },
      { text: "Esporta i lead del quiz in CSV" },
      { text: "Conforme a GDPR e CCPA" },
    ],
  },
  {
    name: "Piano Basic",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mese",
    priceNote: "* Fatturazione mensile",
    priceNoteYearly: "* Fatturazione annuale",
    tagline: "Per store di fascia media in crescita.",
    features: [
      { text: "500 risposte al quiz/mese" },
      { text: "Funzionalità del gratuito +" },
      { text: "Supporto via chat dal vivo" },
      { text: "HTML, CSS e JS personalizzati" },
      { text: "GA4 e Meta Pixel" },
      { text: "Webhooks e Zapier" },
      { text: "Klaviyo, Omnisend e", link: { label: "altre integrazioni", href: "/integrations/" } },
    ],
  },
  {
    name: "Piano Pro",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mese",
    priceNote: "* Fatturazione mensile",
    priceNoteYearly: "* Fatturazione annuale",
    tagline: "Per brand pronti a scalare.",
    features: [
      { text: "1.000 risposte al quiz/mese" },
      { text: "Funzionalità del Basic +" },
      { text: "Supporto via videochiamata" },
      { text: "Account manager" },
    ],
  },
  {
    name: "Piano Premium",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mese",
    priceNote: "* Fatturazione mensile",
    priceNoteYearly: "* Fatturazione annuale",
    tagline: "Brand affermati e multi-mercato.",
    features: [
      { text: "2.500 risposte al quiz/mese" },
      { text: "Funzionalità del Pro +" },
      { text: "Revisione strategica trimestrale" },
      { text: "Piani più grandi -", link: { label: "vedi", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_NL: Plan[] = [
  {
    name: "Gratis plan",
    price: "FREE",
    priceNote: "* Ja, echt!",
    tagline: "Perfect voor nieuwe merken.",
    features: [
      { text: "100 quizreacties/mnd" },
      { text: "Ondersteuning via e-mail" },
      { text: "Maak onbeperkt quizzen" },
      { text: "Aangepast quizontwerp" },
      { text: "Voorwaardelijke logica" },
      { text: "Geavanceerde quizanalyse" },
      { text: "Shopify Markets" },
      { text: "Exporteer quizleads naar CSV" },
      { text: "Voldoet aan AVG en CCPA" },
    ],
  },
  {
    name: "Basic plan",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mnd",
    priceNote: "* Maandelijks gefactureerd",
    priceNoteYearly: "* Jaarlijks gefactureerd",
    tagline: "Voor groeiende middelgrote stores.",
    features: [
      { text: "500 quizreacties/mnd" },
      { text: "Functies van gratis +" },
      { text: "Ondersteuning via live chat" },
      { text: "Eigen HTML, CSS en JS" },
      { text: "GA4 en Meta Pixel" },
      { text: "Webhooks en Zapier" },
      { text: "Klaviyo, Omnisend en", link: { label: "meer integraties", href: "/integrations/" } },
    ],
  },
  {
    name: "Pro plan",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mnd",
    priceNote: "* Maandelijks gefactureerd",
    priceNoteYearly: "* Jaarlijks gefactureerd",
    tagline: "Voor merken die klaar zijn om op te schalen.",
    features: [
      { text: "1.000 quizreacties/mnd" },
      { text: "Functies van basic +" },
      { text: "Ondersteuning via videogesprek" },
      { text: "Accountmanager" },
    ],
  },
  {
    name: "Premium plan",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mnd",
    priceNote: "* Maandelijks gefactureerd",
    priceNoteYearly: "* Jaarlijks gefactureerd",
    tagline: "Gevestigde merken met meerdere markten.",
    features: [
      { text: "2.500 quizreacties/mnd" },
      { text: "Functies van pro +" },
      { text: "Driemaandelijkse strategiereview" },
      { text: "Grotere plannen -", link: { label: "bekijken", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_SV: Plan[] = [
  {
    name: "Gratisplan",
    price: "FREE",
    priceNote: "* Ja, på riktigt!",
    tagline: "Perfekt för nya varumärken.",
    features: [
      { text: "100 quizsvar/mån" },
      { text: "Support via e-post" },
      { text: "Skapa obegränsat antal quiz" },
      { text: "Anpassad quizdesign" },
      { text: "Villkorslogik" },
      { text: "Avancerad quizanalys" },
      { text: "Shopify Markets" },
      { text: "Exportera quizleads till CSV" },
      { text: "Följer GDPR och CCPA" },
    ],
  },
  {
    name: "Basic-plan",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mån",
    priceNote: "* Faktureras månadsvis",
    priceNoteYearly: "* Faktureras årsvis",
    tagline: "För växande mellanstora butiker.",
    features: [
      { text: "500 quizsvar/mån" },
      { text: "Funktioner i gratis +" },
      { text: "Support via livechatt" },
      { text: "Egen HTML, CSS och JS" },
      { text: "GA4 och Meta Pixel" },
      { text: "Webhooks och Zapier" },
      { text: "Klaviyo, Omnisend och", link: { label: "fler integrationer", href: "/integrations/" } },
    ],
  },
  {
    name: "Pro-plan",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mån",
    priceNote: "* Faktureras månadsvis",
    priceNoteYearly: "* Faktureras årsvis",
    tagline: "För varumärken som är redo att skala upp.",
    features: [
      { text: "1 000 quizsvar/mån" },
      { text: "Funktioner i basic +" },
      { text: "Support via videosamtal" },
      { text: "Kontoansvarig" },
    ],
  },
  {
    name: "Premium-plan",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mån",
    priceNote: "* Faktureras månadsvis",
    priceNoteYearly: "* Faktureras årsvis",
    tagline: "Etablerade varumärken med flera marknader.",
    features: [
      { text: "2 500 quizsvar/mån" },
      { text: "Funktioner i pro +" },
      { text: "Kvartalsvis strategigenomgång" },
      { text: "Större planer -", link: { label: "visa", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_FI: Plan[] = [
  {
    name: "Ilmainen paketti",
    price: "FREE",
    priceNote: "* Kyllä, ihan oikeasti!",
    tagline: "Täydellinen uusille brändeille.",
    features: [
      { text: "100 kyselyvastausta/kk" },
      { text: "Sähköpostituki" },
      { text: "Luo rajattomasti kyselyitä" },
      { text: "Räätälöity kyselyn ulkoasu" },
      { text: "Ehdollinen logiikka" },
      { text: "Edistynyt kyselyanalytiikka" },
      { text: "Shopify Markets" },
      { text: "Vie kyselyn liidit CSV:hen" },
      { text: "GDPR- ja CCPA-yhteensopiva" },
    ],
  },
  {
    name: "Basic-paketti",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/kk",
    priceNote: "* Laskutetaan kuukausittain",
    priceNoteYearly: "* Laskutetaan vuosittain",
    tagline: "Kasvaville keskisuurille kaupoille.",
    features: [
      { text: "500 kyselyvastausta/kk" },
      { text: "Ilmaisen ominaisuudet +" },
      { text: "Live-chat-tuki" },
      { text: "Oma HTML, CSS ja JS" },
      { text: "GA4 ja Meta Pixel" },
      { text: "Webhookit ja Zapier" },
      { text: "Klaviyo, Omnisend ja", link: { label: "lisää integraatioita", href: "/integrations/" } },
    ],
  },
  {
    name: "Pro-paketti",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/kk",
    priceNote: "* Laskutetaan kuukausittain",
    priceNoteYearly: "* Laskutetaan vuosittain",
    tagline: "Brändeille, jotka ovat valmiita skaalautumaan.",
    features: [
      { text: "1 000 kyselyvastausta/kk" },
      { text: "Basicin ominaisuudet +" },
      { text: "Videopuhelutuki" },
      { text: "Asiakaspäällikkö" },
    ],
  },
  {
    name: "Premium-paketti",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/kk",
    priceNote: "* Laskutetaan kuukausittain",
    priceNoteYearly: "* Laskutetaan vuosittain",
    tagline: "Vakiintuneet, monen markkinan brändit.",
    features: [
      { text: "2 500 kyselyvastausta/kk" },
      { text: "Pron ominaisuudet +" },
      { text: "Neljännesvuosittainen strategiakatsaus" },
      { text: "Suuremmat paketit -", link: { label: "katso", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_PL: Plan[] = [
  {
    name: "Plan darmowy",
    price: "FREE",
    priceNote: "* Tak, naprawdę!",
    tagline: "Idealny dla nowych marek.",
    features: [
      { text: "100 odpowiedzi quizu/mies." },
      { text: "Wsparcie przez e-mail" },
      { text: "Twórz nieograniczoną liczbę quizów" },
      { text: "Własny projekt quizu" },
      { text: "Logika warunkowa" },
      { text: "Zaawansowana analityka quizów" },
      { text: "Shopify Markets" },
      { text: "Eksportuj leady z quizu do CSV" },
      { text: "Zgodność z RODO i CCPA" },
    ],
  },
  {
    name: "Plan Basic",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/mies.",
    priceNote: "* Rozliczane miesięcznie",
    priceNoteYearly: "* Rozliczane rocznie",
    tagline: "Dla rosnących sklepów średniej wielkości.",
    features: [
      { text: "500 odpowiedzi quizu/mies." },
      { text: "Funkcje planu darmowego +" },
      { text: "Wsparcie przez czat na żywo" },
      { text: "Własny HTML, CSS i JS" },
      { text: "GA4 i Meta Pixel" },
      { text: "Webhooki i Zapier" },
      { text: "Klaviyo, Omnisend i", link: { label: "więcej integracji", href: "/integrations/" } },
    ],
  },
  {
    name: "Plan Pro",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/mies.",
    priceNote: "* Rozliczane miesięcznie",
    priceNoteYearly: "* Rozliczane rocznie",
    tagline: "Dla marek gotowych na skalowanie.",
    features: [
      { text: "1000 odpowiedzi quizu/mies." },
      { text: "Funkcje planu Basic +" },
      { text: "Wsparcie przez rozmowę wideo" },
      { text: "Opiekun konta" },
    ],
  },
  {
    name: "Plan Premium",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/mies.",
    priceNote: "* Rozliczane miesięcznie",
    priceNoteYearly: "* Rozliczane rocznie",
    tagline: "Ugruntowane marki działające na wielu rynkach.",
    features: [
      { text: "2500 odpowiedzi quizu/mies." },
      { text: "Funkcje planu Pro +" },
      { text: "Kwartalny przegląd strategii" },
      { text: "Większe plany -", link: { label: "zobacz", href: "/demo/" }, plus: true },
    ],
  },
];

const PLANS_CS: Plan[] = [
  {
    name: "Plán zdarma",
    price: "FREE",
    priceNote: "* Ano, opravdu!",
    tagline: "Ideální pro nové značky.",
    features: [
      { text: "100 odpovědí na kvíz/měs." },
      { text: "Podpora e-mailem" },
      { text: "Vytvářej neomezeně kvízů" },
      { text: "Vlastní design kvízu" },
      { text: "Podmíněná logika" },
      { text: "Pokročilá analytika kvízů" },
      { text: "Shopify Markets" },
      { text: "Exportuj leady z kvízu do CSV" },
      { text: "Soulad s GDPR a CCPA" },
    ],
  },
  {
    name: "Plán Basic",
    price: "39",
    priceYearly: "31",
    priceSuffix: "USD/měs.",
    priceNote: "* Účtováno měsíčně",
    priceNoteYearly: "* Účtováno ročně",
    tagline: "Pro rostoucí středně velké obchody.",
    features: [
      { text: "500 odpovědí na kvíz/měs." },
      { text: "Funkce plánu zdarma +" },
      { text: "Podpora přes živý chat" },
      { text: "Vlastní HTML, CSS a JS" },
      { text: "GA4 a Meta Pixel" },
      { text: "Webhooky a Zapier" },
      { text: "Klaviyo, Omnisend a", link: { label: "další integrace", href: "/integrations/" } },
    ],
  },
  {
    name: "Plán Pro",
    price: "99",
    priceYearly: "79",
    priceSuffix: "USD/měs.",
    priceNote: "* Účtováno měsíčně",
    priceNoteYearly: "* Účtováno ročně",
    tagline: "Pro značky připravené škálovat.",
    features: [
      { text: "1 000 odpovědí na kvíz/měs." },
      { text: "Funkce plánu Basic +" },
      { text: "Podpora přes videohovor" },
      { text: "Account manažer" },
    ],
  },
  {
    name: "Plán Premium",
    price: "199",
    priceYearly: "159",
    priceSuffix: "USD/měs.",
    priceNote: "* Účtováno měsíčně",
    priceNoteYearly: "* Účtováno ročně",
    tagline: "Etablované značky na více trzích.",
    features: [
      { text: "2 500 odpovědí na kvíz/měs." },
      { text: "Funkce plánu Pro +" },
      { text: "Čtvrtletní strategická revize" },
      { text: "Větší plány -", link: { label: "zobrazit", href: "/demo/" }, plus: true },
    ],
  },
];

export const PLANS_BY_LANG: Record<Lang, Plan[]> = {
  en: PLANS,
  es: PLANS_ES,
  fr: PLANS_FR,
  de: PLANS_DE,
  pt: PLANS_PT,
  it: PLANS_IT,
  nl: PLANS_NL,
  sv: PLANS_SV,
  fi: PLANS_FI,
  pl: PLANS_PL,
  cs: PLANS_CS,
};
